### ISSUE TITLE
Suggestion: Layout

### ISSUE THREAD

**Issue by korishan** [satisfactorymodding/SatisfactoryModManager#10]
Maybe the layout would be better to have the mods list on the left, and then description of any selected mods on the right, instead of the description below.

Also, perhaps add a filter to only show current mods, or all mods (including Outdated).

**Comment by mircearoata** [comment]
Filters will be in the next version, and a redesign will come in the near future (I am completely unable to make anything look/feel nice, so people in the modding community started designing the UI for it and it will be done soon TM)
