### ISSUE TITLE
wont load mods and says mods need update

### ISSUE THREAD

**Issue by funky-monkey123** [satisfactorymodding/SatisfactoryModManager#100]
when I launch the game it shows no mods also every time I open smm it says mod updates available I have updated them at least 30 times in the past 2 days

**Comment by matbrodi** [comment]
Same here

**Comment by matbrodi** [comment]
After removing all mods and reinstalling the SMM, it seems to work fine.

**Comment by nativewolf78** [comment]
I'm having this exact same issue and I think I know why and whats causing it before the mod loader was called sml ( satisfactory mod loader) now it been renamed to smm (satisfactory mod manager ) but in the drop down menu in the mod manager it states satisfactory early access (steam)- CL151248-SML v2.2.1 so it's looking for satisfactory mod loader, not mod manager my icon on my desktop always said sml now it says smm and it's not even satisfactory mod loader 3.00 as it states in the description when clicking to download it here on Github it takes you to SatisfactoryModManager v2.4.3 when clicking on the link that says do not install manually install using the new automatic instaler which it hasn't even installed that version at all steam is requesting satisfactory mod loader version 2,2,1 not satisfactory mod manager 2.4.3 it keeps constantly saying I need to update the mods and its lagging like hell it comes up on some of the mods it tried to install the mod 3 times and to send an error report to the discord so I guess the only option is to do what you have done @matbrodi and remove the mod manager and mods and reinstall my game mods and manager loose all my save again to
