### ISSUE TITLE
Mods not working even if apparently well installed 

### ISSUE THREAD

**Issue by Rem939** [satisfactorymodding/SatisfactoryModManager#102]
I've installed last version of SMM mbut nothing to do ; when I launch Satisfactory update 4 (normal and/or experimental) versions no mods activated... 

I tried lot of things. And I'm a bit lost because no errors messages. 

Thanks for your help.

**Comment by mircearoata** [comment]
Make sure it says that SML 3.1.0 is installed, and not SML 2.2.1, as that version isn't compatible with Update 4, so it won't load at all. If it says SML 2.2.1, then you have some incompatible mods. Either uninstall them and check for updates, or create a new profile in which you install only the compatible mods (this way you also keep the original profile, so when (if) those mods get updated, you can switch to the old profile back)
