### ISSUE TITLE
Mods aren't working in multiplayer

### ISSUE THREAD

**Issue by ManInBoxLV** [satisfactorymodding/SatisfactoryModManager#103]
Mods are working fine if i play single, but if my friend trying to connect to me, he gets crash of the game. 
It works both ways, neither of us can connect to each other.  No matter, how many or what mods we have.
Here's the crash report from my friend's side:
Version: 151248, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Standalone, IsUsingMods: Yes

Assertion failed: GameState [File:C:/jnk/workspace/SML2_sml-dev/SML/Plugins/SML/Source/SML/Private/Module/WorldModuleManager.cpp] [Line: 15]

UE4_Core_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:100]
UE4_Core_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:450]
UE4_SML_Win64_Shipping!AWorldModuleManager::Get() [C:\jnk\workspace\SML2_sml-dev\SML\Plugins\SML\Source\SML\Private\Module\WorldModuleManager.cpp:15]
UE4_SML_Win64_Shipping!TBaseFunctorDelegateInstance<void __cdecl(UWorld::FActorsInitializedParams const &),<lambda_0e16a054ab20a265ccef739e7ee11faf> >::ExecuteIfSafe() [C:\jnk\workspace\SML2_sml-dev\ue4\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:1005]
UE4_Engine_Win64_Shipping!TBaseMulticastDelegate<void,UActorComponent *>::Broadcast() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:1013]
UE4_Engine_Win64_Shipping!UWorld::InitializeActorsForPlay() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\world.cpp:4209]
UE4_Engine_Win64_Shipping!UEngine::LoadMap() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\unrealengine.cpp:12983]
UE4_FactoryGame_Win64_Shipping!UFGGameEngine::LoadMap() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:29]
UE4_Engine_Win64_Shipping!UEngine::TickWorldTravel() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\unrealengine.cpp:12465]
UE4_Engine_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\gameengine.cpp:1686]
UE4_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-160502110050-fad\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:13]
UE4_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4910]
UE4_Win64_Shipping!GuardedMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\launch.cpp:169]
UE4_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:137]
UE4_Win64_Shipping!WinMain() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:268]
UE4_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

And here's message that i get, if i quit to main menu after my friend's disconnection:

![изображение_2021-04-24_222430](https://user-images.githubusercontent.com/83129199/115963895-cddee800-a54b-11eb-8394-d505e3556fcf.png)

**Comment by CosmicInquisitor** [comment]
same here. not a single mod works. If starting with mod loader the other persons game crashes on joining!

**Comment by scottbot95** [comment]
This is not an issue with SMM itself, but the mod loader SML (see satisfactorymodding/SatisfactoryModLoader#81). There's a partial fix for it linked in the ticket comments, although it does not seem to work for all mods. Specifically `Smart!` and `More Milestones + 100` do not work with the patched SML.

**Comment by mircearoata** [comment]
Experimental has now been merged into Early Access, so SML 3.1.0 is the current version on both branches, which means multiplayer works everywhere
