### ISSUE TITLE
[Request for Info]

### ISSUE THREAD

**Issue by Krutonium** [satisfactorymodding/SatisfactoryModManager#108]
Hi, I'm working on a ModLoader Installer for an entirely different game (My Summer Car), and I can't figure out how you guys are editing the arguments for the game in Steam. Could you point me at that part of the code, or tell me how you're doing it?

Thanks for your time, and also thanks for a great modloader. :+1:

**Comment by mircearoata** [comment]
Hi! This is the part of the code that adds `DLLOVERRIDES` to the launch arguments on linux: https://github.com/mircearoata/SatisfactoryModManagerAPI/blob/master/src/installfinders/linux/steam.ts#L59-L108

**Comment by Krutonium** [comment]
Thanks a ton!

**Comment by mircearoata** [comment]
Closing this as I'm cleaning up issues
