### ISSUE TITLE
[Error] Error installing EBmtX1itvNsyDb.

### ISSUE THREAD

**Issue by ethanproulx** [satisfactorymodding/SatisfactoryModManager#111]
I just did a clean install of both Satisfactory and SMM and I get this error on SMM launch and when I attempt to install mods.

**Comment by mircearoata** [comment]
That mod is Throughput Counter, and it is outdated, so SMM fails when trying to install it on the latest game version. Create a new profile (from the button to the right of the profiles box) and install the compatible mods that you have in the current profile.
