### ISSUE TITLE
Constant Satisfactory crashing while using SMM

### ISSUE THREAD

**Issue by mrtoes** [satisfactorymodding/SatisfactoryModManager#112]
I am only using 3 mods; Pak Utility Mod, Smart! and Daisy Chain Power Cables. Things started fine and was able to get some progress going and now out of nowhere after loading a save and leaving where I spawned I get a crash with the following response:

"Version: 152331, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Listen Server, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000018

FactoryGame_D3D11RHI_Win64_Shipping!FD3D11DynamicRHI::RHISetShaderUniformBuffer() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\windows\d3d11rhi\private\d3d11commands.cpp:658]
FactoryGame_RHI_Win64_Shipping!FRHICommandListExecutor::ExecuteInner_DoExecute() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\rhi\private\rhicommandlist.cpp:331]
FactoryGame_RHI_Win64_Shipping!FRHICommandListExecutor::ExecuteInner() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\rhi\private\rhicommandlist.cpp:603]
FactoryGame_RHI_Win64_Shipping!FRHICommandListBase::~FRHICommandListBase() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\rhi\private\rhicommandlist.cpp:859]
FactoryGame_RHI_Win64_Shipping!FRHICommand<FRHICommandWaitForAndSubmitSubList,FRHICommandWaitForAndSubmitSubListString1012>::ExecuteAndDestruct() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\rhi\public\rhicommandlist.h:744]
FactoryGame_RHI_Win64_Shipping!FRHICommandListExecutor::ExecuteInner_DoExecute() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\rhi\private\rhicommandlist.cpp:331]
FactoryGame_RHI_Win64_Shipping!TGraphTask<FExecuteRHIThreadTask>::ExecuteTask() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\public\async\taskgraphinterfaces.h:849]
FactoryGame_Core_Win64_Shipping!FNamedTaskThread::ProcessTasksUntilQuit() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\async\taskgraph.cpp:586]
FactoryGame_RenderCore_Win64_Shipping!FRHIThread::Run() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\rendercore\private\renderingthread.cpp:290]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-210421141322-21c\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:86]"

Any possible fixes or anything I should be doing different?

**Comment by mircearoata** [comment]
SMM simply downloads files (SML and mods) to the right location, it doesn't hook the game or load mods, so SMM is not the problem. And the crash is coming from rendering, so it's unlikely it's caused by a mod either. Have you tried turning mods off in SMM and checking if it still happens?
