### ISSUE TITLE
Error No Satisfactory installs found.  How to solve it?

### ISSUE THREAD

**Issue by Cloud2702** [satisfactorymodding/SatisfactoryModManager#114]
![QQ浏览器截图20210611062208](https://user-images.githubusercontent.com/85711992/121604603-70601580-ca7d-11eb-825e-23fb54baf4b3.png)
The system has been reinstalled, and there has been an error after installing mod Manager. What is the problem?

**Comment by scooper93** [comment]
Are you running the game with it installed to another drive other than C:\ - if so the mod manager won't install - Just fixed this problem on my machine this way. You might need to reinstall the mod manager.

**Comment by Cloud2702** [comment]
Disk C is for the system, and my solid state is only 120g. Can you tell me why I put disk C? How big is the game? don't you have a B count in mind? Before reinstalling the system, the game is placed on the mechanical hard disk E disk, the mod manager can be used, but forgot how to install it.

**Comment by mircearoata** [comment]
SMM should find the game on any drive, but the format of one of the Steam files (the one listing the libraries) has changed, so it breaks SMM on newly installed Steam

There is an [unreleased version](https://drive.google.com/file/d/1iVVSZK2adOKCQDIvKjxgj1tlCi6QL4Zw/view?usp=sharing) that I've been sending to people on the modding discord when they ran into this for the last couple of days. It is unreleased for now because there are some more things I'm working on for this update (such as disabling mods in a profile without completely uninstalling the mod from the profile, making it easier to debug or just temporarily disable a mod), which aren't ready just yet.

**Comment by Cloud2702** [comment]
Is there any way to solve the problem? There was no problem with the installation before, but now I have forgotten how to install it.

**Comment by mircearoata** [comment]
As I said, you can install the version I linked and it will fix the issue. Just download it and install it like you did for the SMM you currently have

**Comment by Cloud2702** [comment]
I don't know much about this website. Could you please tell me where to open the link and download the address? thank you.

**Comment by mircearoata** [comment]
This is the link in my previous message ![Screenshot_20210611-222028_GitHub.jpg](https://user-images.githubusercontent.com/19414258/121738736-46e9cd00-cb03-11eb-9c19-da116f59ce55.jpg)

**Comment by Cloud2702** [comment]
Yes, but I can't access it after clicking in. I don't know if it's my network problem. What if some foreign websites can't be accessed?

**Comment by mircearoata** [comment]
The fix is also in SMM v2.5.0 now.

**Comment by Rupster009** [comment]
You probably have the game pirated so it wont work.

**Comment by Sloth-on-meth** [comment]
having this issue too [log](https://pastebin.1a38.nl/new?level=success&glyph=fas%20fa-check&msg=The%20paste%20has%20been%20successfully%20created:&url=pastebin.1a38.nl/HB1sW5t2jsAomIl0VtwiS)

**Comment by tadde-rep** [comment]
same problem...

**Comment by PR0G4M3R** [comment]
> SMM should find the game on any drive, but the format of one of the Steam files (the one listing the libraries) has changed, so it breaks SMM on newly installed Steam
> 
> There is an [unreleased version](https://drive.google.com/file/d/1iVVSZK2adOKCQDIvKjxgj1tlCi6QL4Zw/view?usp=sharing) that I've been sending to people on the modding discord when they ran into this for the last couple of days. It is unreleased for now because there are some more things I'm working on for this update (such as disabling mods in a profile without completely uninstalling the mod from the profile, making it easier to debug or just temporarily disable a mod), which aren't ready just yet.

Could you send me this please? When i click on the link it says it doesnt exist,
