### ISSUE TITLE
SatisfactoryModManager Stays in TaskBar

### ISSUE THREAD

**Issue by dreyervorster** [satisfactorymodding/SatisfactoryModManager#115]
So I installed the mod manager, but when I open it, it stays in the taskbar and when I click to bring it up on the screen nothing happens. When I hover over the icon on the taskbar I can see the small screen showing the mods I have installed. So I deleted all my mods and folders and uninstalled SMM and reinstalled and its still the same issue.

![SMM_Screenshot](https://user-images.githubusercontent.com/81566429/122268817-d1a04280-cedc-11eb-97bd-e84125262c63.PNG)

**Comment by dreyervorster** [comment]
If anyone have this issue I just got a fix for it. Right-Click on the Satisfactory Mod Manager Icon on your desktop and click on properties, then click on the dropdown next to run and c
![Uploading SMM_Fix_Screenshot.PNG…]()
hoose Maximmized

**Comment by MuseMKR** [comment]
Please reopen this issue, as the fix listed here does not work.

**Comment by mircearoata** [comment]
See issue #154

**Comment by MuseMKR** [comment]
Thank you. The issue has been fixed.
