### ISSUE TITLE
Multiple Installs do not lead to multiple launching options and mods installing in the wrong location

### ISSUE THREAD

**Issue by IdioticProphet** [satisfactorymodding/SatisfactoryModManager#119]
So I recently installed SMM, and tried to install mods. Immediately I noticed the mods didn't work and nothing changed. After some troubleshooting and help from the discord I realized that SMM was installing mods to an instance of the game I forgot I had on my W:\ drive instead of the install I was launching which was on my C:\ drive.

digging around in the code I believe this has to do with how instances are discovered somewhere in `src/renderer/store.js`, along with this the `Install:` section only had one instance, and didn't change after I deleted my second instance of the game.
![image](https://user-images.githubusercontent.com/20072862/126909283-af1b10a8-1c7d-47a1-a29f-105dc5093a51.png)

The **ideal** remedy is each end-user not having two instances of the game.
But it could also be beneficial to have some dialog that tells you where SMM *thinks* your install location is with the ability to modify it by hand, since smooth brains like me exist with two accidental installs of the same game. This is most comparable to Minecraft modding and being able to select what instance of Java you want to use, or where you want a modded instance to be installed (although not a perfect parallel).

**Comment by mircearoata** [comment]
The installs had the same name so the combo box only displayed one of them. I changed it in v2.6.0 so that it uses the install location as the item ID, and also added a tooltip for the found install path so that it is easy to check if a wrong location the issue.
