### ISSUE TITLE
Download rate shown is incorrect

### ISSUE THREAD

**Issue by klAvAx** [satisfactorymodding/SatisfactoryModManager#121]
**Description:**
I just noticed that SMM shows bogus download rate which is actually impossible to get with my internet connection, also shown download rate shown is almost always increasing and not fluctuating like it should.

**Bug:**
Shown download rate shows incorrect download rate average

**Shown download rate:**
<img width="365" alt="Untitled" src="https://user-images.githubusercontent.com/600550/127753109-e96ef3c0-9199-4e6a-923e-8115d5359a90.png">

**Internet speed average tested with Speedtest after mod updates finished:**
<img width="542" alt="real speed" src="https://user-images.githubusercontent.com/600550/127753114-31ac001a-fcf9-4046-9ca8-63359326d33c.png">

**Comment by AstroFloof** [comment]
Looks fine to me...
You might be misreading the information given. 
The information is displayed as
`A` files: `B` | `C` / `D` | `E` | `F`
where
A = number of files
B = percent completion (calculated as C÷D)
C = current amount of data downloaded (measured in megabytes)
D = total amount of data required to be dowloaded (measured in megabytes)
**E = current download speed (measured in kbps - oof)**
F = predicted time to finish downloading (D-C) ÷ E

Your maximum speed according to speedtest.net is one megabits per second, or 1,000,000 bits/sec
SMM is downloading at 374.38 kilobits per second, or 374,380 bits/sec - well under your theoretical maximum speed.
At this speed, that amount of data would take about 16.6 minutes to download.
`46.63 Megabytes (373040000 bits) ÷ 374380 bits/sec ÷ 60 sec/min = 16.6070125 minutes`

**Comment by klAvAx** [comment]
Thanks for a reply, here where i live all ISP's have the same abysmal internet speed, ADSL on the end of the line, theoretical maximum of 6Mbps and real life maximum of 2Mbps from the monitoring i've done... From the stuff i heard about modernization i have only hope left to wait for better *ahem* times related to internet speed.
Anyway from the acronyms i have met usually when someone writes KB (note the caps) they usually mean Kilobytes which is 8 times of kilobit, maybe my logic is flawed but i kind of believe the software should show Kb/s if its kilobits. Most of the other software does the same, even on linux i see KB/s which never exceeds 250KB/s

P.S. Currently my ISP connection maximum is ~2Mbit/s so that would be roughly 244.14KiB/s or 250KB/s so displayed speed such as 374.38KB/s is not possible more likely it is 45.7KiB/s or 46.8KB/s, Even with 1Mbit/s that would be correct because maximum for that is 122.07KiB/s or 125KB/s

**Comment by AstroFloof** [comment]
Ah I see, yeah that is somewhat confusing.

**Comment by klAvAx** [comment]
For example i am updating ETS2 via Steam now and stats look like this, Note the **peak speed**:
<img width="1039" alt="steam pvz" src="https://user-images.githubusercontent.com/600550/138323951-66419485-640b-4321-aaad-88a09b25c082.png">

**Comment by mircearoata** [comment]
SMM v2.6.0 now properly removed finished downloads from the speed calculation.
