### ISSUE TITLE
Cannot uninstall a mod 

### ISSUE THREAD

**Issue by Apexio20** [satisfactorymodding/SatisfactoryModManager#124]
i installed the mod logistics 2.0 from xDarix.

The game log showed some errors, so i wanted to uninstall this mod.
but in mod manager is shown up that logistics 2.0 is a dependency from logistics 2.0. 
thats why i cannot uninstall it.

clearing the files from mod folder doesnt help, because mod manager installs all files again.
how can i get this fixed?

would be good to get an option for this. for now, maybe there is a file for config or such where mods get listed, so that i can clear this manually. but i dont know if yes and if yes, where to find this file for clearing.

upto now, i installed about 249 mods via mod manager. but game crashed several times, even when using only compatible mods. so i searched a long time for and into the log files to find all errors. in this way i uninstalled many mods, at the end i only had about 130 mods activated which includes dependencies.
this seem to work so far, but the logs are still full of warnings.

in former times i had this mod manager with many mods installed, which all worked perfectly. i had so much more extra modded content without issues. now i dont know if the problem is the mod manager or the mods, even when both are updated.

i also installed a new version of the mod manager and put in sml manually with latest version. mod manager checked it too, so latest install is activated.

nevertheless, i hope to get this solved to uninstall this mod logistics 2.0, as described.

**Comment by Apexio20** [comment]
im sorry, i found the solution. 

i had to deactivate this mod which button was shown on the info window from mod manager. then was shown uninstall. and when deactivated, i could uninstall it.

usually all mods can be uninstalled directly without deactivating them, unless it is a dependency.

**Comment by mircearoata** [comment]
That mod was a dependency of itself, which SMM did not account for. It now does in v2.6.0, so the mod can be uninstalled.
