### ISSUE TITLE
Cant launch game with ModManager

### ISSUE THREAD

**Issue by CosmicInquisitor** [satisfactorymodding/SatisfactoryModManager#127]
after the newest experimental updates i cant seem to get the game started via mod manager.
i get those errors (see files attached)
I already tried to uninstall some of the mods but it wont do any difference
![satis2](https://user-images.githubusercontent.com/83359927/137638858-f40b9dcc-3fed-4c08-b27b-720a98df8914.PNG)
![satis3](https://user-images.githubusercontent.com/83359927/137638862-a08b8ac1-20b7-40d6-8925-add0835b8008.PNG)

anyone able to help?

**Comment by AstroFloof** [comment]
Mods don't work on experimental right now.
If you are just starting using mods, and have saved games in Experimental before, don't use mods for now. Early Access can't open saves made in Experimental.
If you have used mods before and are just trying out Experimental, switch back to Early Access, or your mods don't work.
Next time you have an issue with this, come to the discord https://discord.gg/satisfactorymodding

**Comment by mircearoata** [comment]
This was a SML issue. It was updated on November 23rd, so make sure you use the latest version of it (SML 3.2.0) - check for updates from SMM to get it.
