### ISSUE TITLE
"Mods" toggle button has confusing behavior.

### ISSUE THREAD

**Issue by Ryder17z** [satisfactorymodding/SatisfactoryModManager#129]
Hello.
I was told SMM should keep track of EA and EXP versions separately on discord, but from some testing it doesn't seem to behave correctly.

The issue: if i switch mods off on EXP and then switch to EA, then back to EXP, the mods toggle is re-enabled.

[SMM_mods_toggle_button.mp4.txt](https://github.com/satisfactorymodding/SatisfactoryModManager/files/7553092/SMM_mods_toggle_button.mp4.txt) (remove .txt to view since github can't show mp4 screen recordings)

While i doubt it, it is possible that this is a system-specific bug.
I'm running Manjaro XFCE.

**Comment by mircearoata** [comment]
Fixed in v2.6.0
