### ISSUE TITLE
SatisfactoryModManager is still loading and loading and loading 

### ISSUE THREAD

**Issue by Brandstifter22** [satisfactorymodding/SatisfactoryModManager#132]
hello my SatisfactoryModManager is still loading and loading and loading.... what is the problem ? i open it and wait like 10 minutes than i close it and try again... but is not working 
![satisfactory - Discord_211125140259](https://user-images.githubusercontent.com/95075831/143556267-5cdd88c5-7560-4c47-93c9-3fb7c97da989.png)

**Comment by mircearoata** [comment]
See #133
