### ISSUE TITLE
SMM Infinite Load Issue

### ISSUE THREAD

**Issue by Fhwagod** [satisfactorymodding/SatisfactoryModManager#133]
SMM is stuck loading forever. I deleted an old profile and ever since then it has not worked properly.

I have attempted to delete and reinstall several times along with restarting my computer between reinstall attempts.

I have also deleted any and all local files in %localappdata% between uninstalling and reinstalling SMM

Any advice and help is very much appreciated

**Comment by mircearoata** [comment]
Open `%appdata%\SatisfactoryModManager\settings.json` and in the `selectedProfile` field replace the name of the profile you deleted (or any profile name that looks invalid - in some cases dates), with `modded`, a profile that always exists, so it can load it

**Comment by Brandstifter22** [comment]
> Open `%appdata%\SatisfactoryModManager\settings.json` and in the `selectedProfile` field replace the name of the profile you deleted (or any profile name that looks invalid - in some cases dates), with `modded`, a profile that always exists, so it can load it

TY so much !!!

**Comment by mircearoata** [comment]
Fixed in v2.6.0
