### ISSUE TITLE
Linux Update Hang.

### ISSUE THREAD

**Issue by IMarvinTPA** [satisfactorymodding/SatisfactoryModManager#138]
When launching Satisfactory-Mod_Manager.AppImage, the console log reports:
```
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
20:04:02.387 › Checking for update
20:04:03.313 › Update for version 2.5.0 is not available (latest version: 2.5.0, downgrade is disallowed).

```
And the update progress bar stops at about 5%.  The application basically freezes and is non-responsive.

**Comment by IMarvinTPA** [comment]
I'm still getting the error message, but after rebooting, it at least doesn't halt at the point reported above.

**Comment by MetalJulia** [comment]
Same issue here, developer tools are useless in this hanging state so I can't debug it. Attempts to build and debug locally have been useless too, just get weird errors.

**Comment by mircearoata** [comment]
Closing as this was a SMM2 issue, and SMM3 is now released
