### ISSUE TITLE
Corrupt profile bug is back. 

### ISSUE THREAD

**Issue by Ryder17z** [satisfactorymodding/SatisfactoryModManager#141]
So I previously had to make a new profile because the one I was using stopped working. I can't enable or disable mods for it.

After asking on discord, it seems that the best solution was to create a new profile and add the compatible mods to the new profile.

And what happens when I launch SMM today?
I get hit by the same issue.

Please fix this. These profiles can not be exported/imported.

**Comment by Ryder17z** [comment]
And for some reason I can't even generate the debug info at the moment.

**Comment by mircearoata** [comment]
Closing as this was a SMM2 issue, and SMM3 is now released. SMM3 is also more lenient with performing profile changes while there are errors
