### ISSUE TITLE
Failed to register win-ca 

### ISSUE THREAD

**Issue by semyag** [satisfactorymodding/SatisfactoryModManager#145]
Attempting to run SMM on Pop-OS, the app will open and it gets stuck on loading. In the logs I get the following repeated.
[SatisfactoryModManager-2022-01-31.log](https://github.com/satisfactorymodding/SatisfactoryModManager/files/7973377/SatisfactoryModManager-2022-01-31.log)
 
I tried to run an earlier version however the Manager just updates restarts and does the same. Did I need to do anything special for installation? I have Satisfactoy installed under steam using (deb) installation.

**Comment by mircearoata** [comment]
The win-ca error is to be expected on linux (as the name suggests, it's a windows-only module), although I did notice it happening a lot on windows too, but that's a different issue.

Check the chromium devtools (ctrl+shift+i or F12) console for errors and send the ones you find.

**Comment by semyag** [comment]
> The win-ca error is to be expected on linux (as the name suggests, it's a windows-only module), although I did notice it happening a lot on windows too, but that's a different issue.
> 
> Check the chromium devtools (ctrl+shift+i or F12) console for errors and send the ones you find.

Are you saying the flatpack is meant for windows?

And when I look at the chromium devtools if I download an earlier version I see that its trying to update (which reflects in the GUI) and then it restarts before I can snag the logs. However when it reboots it just says loading and no events are showing in the chromium devtools.

**Comment by semyag** [comment]
Okay I guess for future references, I was able to get this to work on manjaro with no issues. So I downloaded appimagelauncher and downloaded SMM appimage. Used the appimagelauncher to download and run SMM. Rebooted and then restarted SMM and sure enough it worked.

**Comment by mircearoata** [comment]
Closing as this was a SMM2 issue, and SMM3 is now released
