### ISSUE TITLE
SMM Mods are not showing & deleting previous installed mods (Steam)

### ISSUE THREAD

**Issue by xXAkaGeXx** [satisfactorymodding/SatisfactoryModManager#146]
SMM was working for me yesterday. But now I'm having this huge issue which makes SMM very useless since I can't find or install mods from the app and automatically deleting my previous mods.

I tried signing in on Ficsit.app as well. I can't seem to login even though I have an account via GitHub

**Comment by mircearoata** [comment]
ficsit.app had some issues that day, and without it there isn't much SMM can do. However, removing mods when that happens is definitely not intended, and I will release a fix for that soon.

**Comment by mircearoata** [comment]
Finally released v2.8.0 which adds offline support.
