### ISSUE TITLE
[BUG] The 2.8 installer thinks the mod manager is open when it is not stopping it from updating

### ISSUE THREAD

**Issue by gibbs160** [satisfactorymodding/SatisfactoryModManager#150]
The installer 2.8 fails to update correctly and it makes the main application fail as well.  The Mod Manager application checks for an update and launches the 2.8 installer crashing it.  If you uninstall you use the 2.8 installer and it crashes as well.

**Comment by mircearoata** [comment]
Closing as this was a SMM2 issue, and SMM3 is now released
