### ISSUE TITLE
SMM window not visible but icon shows in taskbar

### ISSUE THREAD

**Issue by killshock360** [satisfactorymodding/SatisfactoryModManager#154]
its in my taskbar on windows but no matter what i do, i can not bring it up to where i can interact with it at all

**Comment by mircearoata** [comment]
The saved window position probably got corrupted, placing the window offscreen. You can try, with SMM closed, setting both values (`x` and `y`) for `windowLocation` to 0.

**Comment by Zenkuko** [comment]
How do i go about doing this ?

**Comment by budak7273** [comment]
> The issue is that the window somehow got offscreen. To fix it you need to go in `%appdata%\SatisfactoryModManager\settings.json` and in `windowLocation` set the x and y to 0 to bring the window back on the screen. Restart SMM after you do that

This is the message we have FICSIT-Fred set to send on the discord.

**Comment by mircearoata** [comment]
Closing as this was a SMM2 issue, and SMM3 is now released
