### ISSUE TITLE
Recurring problem where a profile will only run once and then not. (Have to toggle mods on/off multiple times and restart SMM to get the same profile to work again)

### ISSUE THREAD

**Issue by Ryder17z** [satisfactorymodding/SatisfactoryModManager#156]
I mentioned this a while back on discord but it kinda got lost in there.

I don't know where to begin with this issue but it's been happening on 3 different profiles that I've created.

Once some odd combination of mods are present in a profile, the game will only run with this profile once.
It will not reach the main menu until mods are toggled off/on and SMM is restarted, this sometimes takes multiple attempts, but eventually this allows the game to successfully load once more.

Then after you exit the game, you have to go through the same process again when you want to play again with this profile

**Comment by mircearoata** [comment]
Closing as it is an old issue, and does not seem to be a SMM issue, SMM does not touch the mod files unless you perform an action in SMM. Without additional info, my guess is that this was the hooking crash that sometimes happens, but should be reduced in SML 3.8.0
