### ISSUE TITLE
SMM Unexpected shutdown or exit

### ISSUE THREAD

**Issue by p1H3u7u7n5** [satisfactorymodding/SatisfactoryModManager#158]
When I try to launch SMM It flashes up for moment and then it auto closes or exits.

Unable to capture as this happens for a split second with auto update enabled. 

Believe it is with 2.9.1

**Comment by AstroFloof** [comment]
Does this still occur with 2.9.2?

**Comment by mircearoata** [comment]
Closing as this was a SMM2 issue, and SMM3 is now released
