### ISSUE TITLE
Add "installed" option to sort choice (enhancement)

### ISSUE THREAD

**Issue by ComputerJock** [satisfactorymodding/SatisfactoryModManager#159]
It would be useful if one could sort the mods such that the installed mods were grouped together. As there are (for me) 535 possible mods, it is error prone to scroll through all the mods and potentially miss one.

**Comment by AstroFloof** [comment]
You can already filter by Installed
![image](https://user-images.githubusercontent.com/80119007/201507284-0e5b0ddb-3a11-431d-9087-e57b7e379a53.png)

![image](https://user-images.githubusercontent.com/80119007/201507278-e2985937-74de-4b85-b1e0-bb9be32daf2e.png)
