### ISSUE TITLE
Black screen issue potentially due to old electron for AppImage

### ISSUE THREAD

**Issue by jimmon89** [satisfactorymodding/SatisfactoryModManager#160]
I ran into a black screen while using the AppImage of SMM after a reinstall of [Nobara Linux](https://nobaraproject.org/) brought on by an unrelated issue.
running it in a terminal revealed the following error
`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`
which pointed me to an [Issue on the BitWarden GitHub](https://github.com/bitwarden/clients/issues/2661).
The error message was caused by the environment variable `LIBVA_DRIVER_NAME` being null.
So following the info in the github issue ticket i tried `env LIBVA_DRIVER_NAME=nvidia ./Satisfactory-Mod-Manager.AppImage`.
which got rid of the error, but the black screen remained.
then someone had an unusual request and said to "bear with them", and try `nouveau` as the driver name.
so following along i ran `env LIBVA_DRIVER_NAME=nouveau ./Satisfactory-Mod-Manager.AppImage` and for the people in the ticket as well as myself it worked.
according to the developers of BitWarden, the problem was caused by using an old version of Electron and upgrading to a newer version fixed the black screen issue.
### **What is expected:**
to have a working application when launched with 
`env LIBVA_DRIVER_NAME=nvidia ./Satisfactory-Mod-Manager.AppImage`

### **What Happens:**
A black window leading to an unusable application

### **Workaround:**
Launch with
`env LIBVA_DRIVER_NAME=nouveau ./Satisfactory-Mod-Manager.AppImage` 

### **Possible permanent Fix:**
upgrade the pipeline to a newer version of electron

### **My System:**
**Desktop Ennvironment:** Gnome 42.4
**Windowing System:** Wayland
**OS Name:** Nobara Linux 36 (Based on Fedora 36)
**GPU:** NVIDIA GeForce RTX 3060
**Nvidia Driver Version:** 515.65.01
**NVML Version:** 11.515.65.01
**GPU Memory** 12288 MB
**PCI Device ID:** 0x2503
**PCI Vendor ID:** 0x10de
**PCIe Generation:** Gen3
**CPU:** AMD Ryzen 5 3400G with Radeon Vega Graphics
**RAM:** 32.0 GiB

More info available upon request

**Comment by budak7273** [comment]
(Copied from discussion on the discord)
The actual solution will be not using electron anymore sometime™️, so upgrading electron 5 major versions of breaking changes just to ditch electron not too long after that doesn't sound that great

**Comment by jimmon89** [comment]
> (Copied from discussion on the discord) The actual solution will be not using electron anymore sometimetm, so upgrading electron 5 major versions of breaking changes just to ditch electron not too long after that doesn't sound that great

**(Also posted in discord)**
Fair point

**(Not from discord)**
it would indeed make more sense not to go through the trouble of upgrading the pipeline to a newer version of electron if you already want to ditch electron as a whole

**Comment by mircearoata** [comment]
Closing as this was a SMM2 issue, and SMM3 is now released, no longer using electron
