### ISSUE TITLE
Mod manager not showing

### ISSUE THREAD

**Issue by DT5555** [satisfactorymodding/SatisfactoryModManager#161]
The mod manager is shown to be open, when I hover over it a page is shown. but it won't let me access the page, it just doesn't show on the screen

**Comment by mircearoata** [comment]
The issue is that the window somehow got offscreen. To fix it you need to go in `%appdata%\SatisfactoryModManager\settings.json` and in `windowLocation` set the `x` and `y` to 0 to bring the window back on the screen. Restart SMM after you do that

**Comment by DT5555** [comment]
%appdata%\SatisfactoryModManager\settings.json isn't showing up in the file explorer. is there anywhere else i can find it?

**Comment by DT5555** [comment]
if i spam click on the taskbar app, it shows up as a white screen for a quarter of a second

**Comment by DT5555** [comment]
you just have to fully uninstall the mod manager and reinstall it, and not open it from the place you installed it from
