### ISSUE TITLE
Vulkan installation broken after using SMM

### ISSUE THREAD

**Issue by moan0s** [satisfactorymodding/SatisfactoryModManager#162]
# Error description

I wanted to try out mods and downloaded the SMM AppImage (System details see below)
I installed one mod and pressed "Launch Satisfactory" which greeted me with the error message `A D3D11 compatible GPU (Feature Level 11.0, Shader Model 5) is required to run the engine.`

This is kinda odd as I always had `Vulkan shader processing` on game startup so I assumed I used vulkan before that.

Trying to run the game from steam results in the same error, even after deleting the `Mods/` Folder.

When i tried to force vulkan with `-vulkan` I got the error message `Cannot find a compatible vulkan driver (ICD)`. Checking my Vulkan installation with `vulkaninfo` results in the following error message:
```
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.3.226/vulkaninfo/vulkaninfo.h:672:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER

```

I am not sure how to tackle this issue. What I tried is using `export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` from [here](https://wiki.archlinux.org/title/Vulkan#Troubleshooting) which did not help.

I am reasonably sure that the SMM did this as I did no updates etc... between shutting down the game, runnning SMM and restarting it.

# System Info

OS: EndeavourOS Linux x86_64
Host: 20YM Lenovo ThinkBook 16p Gen 2
Kernel: 5.19.13-arch1-1 
DE: Plasma 5.25.5
WM: kwin
CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 3.300GHz
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q

**Comment by moan0s** [comment]
![image](https://user-images.githubusercontent.com/25753802/195641063-e2f1eaa1-6efe-4807-bd6a-b583d3539de8.png)

Well out of frustration I restarted my system and... it works again? No idea what happend. Maybe still worth following up on so I'll leave this open but feel free to close

**Comment by mircearoata** [comment]
SMM doesn't do anything besides placing the mod files files in the `FactoryGame\Mods` folder, and it surely doesn't do anything related to graphics drivers, so it's not SMM causing it
