### ISSUE TITLE
SMM is no longer working since update, while Avast Antivirus is active 

### ISSUE THREAD

**Issue by jayjay3108** [satisfactorymodding/SatisfactoryModManager#168]
I get the following message:
Threat blocked
we have blocked satisfactory-mod-manager.exe because it was infected with IDP.Generic.

Adding exception does not fix the problem, because the message comes right back. Reinstalling does not work either, because it blocks the installer directly.

**Comment by ZZWolf47** [comment]
same here :(

**Comment by Ryder17z** [comment]
In Avast, turn off "real time protection", install SMM, turn back on. And it will hopefully work.
Avast and other modern AV software uses pattern recognition in files to look for potential threats, which is basically an educated guess.

**Comment by mircearoata** [comment]
Closing as this was a SMM2 issue, and SMM3 is now released, being code signed as well, which should reduce the amount of antivirus false positives
