### ISSUE TITLE
[Request] Please add support for Heroic Games Launcher

### ISSUE THREAD

**Issue by pioj** [satisfactorymodding/SatisfactoryModManager#171]
First of all, thanks for the support. This is a must-have tool for Satisfactory and every mod is now using it as a requirement...

Mod Manager can't find my current installation of the game. It was installed from the Heroic Games launcher, which is an alternative way for installing and running games from GOG and the EpicGamesLauncher app.

Shouldn't be possible to add support for it, or at least let the user change the default expected path where to find the game install folder?

Thank you.

**Comment by salmon85** [comment]
A work around for now since I'm in the same boat as yourself.

I looked at the debug logs and noticed it's either looking for steam (flatpak) or legendary
so I downloaded legendary
https://github.com/derrod/legendary

legendary auth
login to your epic account
paste in the key into legendary
legendary import CrabEA /folder_where_satisfactory_is_located_for_you   for me I used the command legendary import CrabEA /home/user/Games/Heroic/SatisfactoryEarlyAccess

run the Satisfactory-Mod-Manager.AppImage

**Comment by Evolis3d** [comment]
Thank you, but I'm on Windows. Your fix won't work on my computer...

**Comment by flerouwu** [comment]
@salmon85 Another way to synchronize Legendary and Heroic configs:

**Note:** This is done under Linux and non-flatpak version of Heroic. This should be possible on Windows using directory junctions or similar.

<details>
<summary>View Instructions</summary>

1. Install Legendary system-wide. Arch users can install from the [AUR](https://aur.archlinux.org/packages/legendary).

2. Remove current Legendary config directory (if it exists).
	```
	$ rm -rf ~/.config/legendary
	```

3. Symlink Heroic's Legendary config path to Legendary's default path.
	```
	$ ln -s ~/.config/heroic/legendaryConfig/legendary/ ~/.config/legendary
	```

4. Setup Heroic to use a custom Legendary binary.
	For me, this is installed in `/usr/bin/legendary`. Use `which legendary` to find your install location.
	In Heroic, go to *Settings > Advanced* and change the Alternative Legendary Binary path.

5. Ensure Legendary is working.
	```
	$ legendary status
	$ legendary list-installed
	```
	
	The above commands should show your username and your installed games.

6. Launch SMM. It should find your Legendary (Heroic) game install.
</details>

**Comment by mircearoata** [comment]
SMM3 now supports the new Heroic configuration, on both Windows and Linux
