### ISSUE TITLE
"Create Desktop Shortcut" doesn't do anything in SMMv3 installer

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/SatisfactoryModManager#181]
https://discord.com/channels/555424930502541343/1193986432574963782/1194464273796182096

**Comment by mircearoata** [comment]
Could not reproduce in either the version of that time, or in the latest beta. Creating the shortcut has also been moved to the "components" page of the installer.

If this is still an issue, check the installation log for the location where it mentions a shortcut is created.
