### ISSUE TITLE
SMM3: When zoomed in, the button to launch the game is unclickable

### ISSUE THREAD

**Issue by Th3Fanbus** [satisfactorymodding/SatisfactoryModManager#183]
As per https://discord.com/channels/555424930502541343/555782140533407764/1200205253946118244

<img width="963" alt="image" src="https://github.com/satisfactorymodding/SatisfactoryModManager/assets/22937129/2edcf3b9-5990-4970-a44e-7ce887088f71">

**Comment by FabiusHaselnuss** [comment]
The update window has the same problem as the button Update all is not visible at a screen size of 150%.

**Comment by mircearoata** [comment]
Fixed in beta.2
