### ISSUE TITLE
SMM3: Cannot find SMM logs anywhere

### ISSUE THREAD

**Issue by Th3Fanbus** [satisfactorymodding/SatisfactoryModManager#185]
It seems that logging is not functional on SMM v3.0.0-beta.1 for some reason. There are no logs in `%LOCALAPPDATA%\SatisfactoryModManager\logs` or the debug zips.

https://discord.com/channels/555424930502541343/555782140533407764/1203705597413818388

**Comment by mircearoata** [comment]
Fixed in beta.2
