### ISSUE TITLE
Make it more obvious that links are links

### ISSUE THREAD

**Issue by Th3Fanbus** [satisfactorymodding/SatisfactoryModManager#191]
For example, underline links. I am so sick and tired of having people post a screenshot of this error message instead of following the instructions written in there...

![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/22937129/5edea1b8-68f6-48c2-845f-4f3ce4a142a9)

**Comment by budak7273** [comment]
SMMv3 has a different popup for this that has a button that says "generate debug info" (as opposed to clickable text) that will hopefully help with this
