### ISSUE TITLE
SMMv3 Window Size Compatibility

### ISSUE THREAD

**Issue by xXdrewbaccaXx** [satisfactorymodding/SatisfactoryModManager#192]
Display resolution of 1920x1080 breaks SMMv3's window.

You cannot close the expanded drawer after clicking on a mod, nor can you scroll.

Uploading Discord_df5GiSk03s.mp4…

**Comment by gOOvER** [comment]
cant confirm this. Works for me

**Comment by xXdrewbaccaXx** [comment]
> cant confirm this. Works for me
Video uploaded here. It failed in the original post.
https://discord.com/channels/555424930502541343/830842478956642354/1218617757046935552

**Comment by mircearoata** [comment]
Checking the video uploaded on discord, this issue has been fixed in beta.2 by improving the responsivity of UI elements, as well as adding scrollbars to any vertical surface that would become unreadable if it was any smaller
