### ISSUE TITLE
Latest SMM beta does not list Samba shares when adding servers by path

### ISSUE THREAD

**Issue by SpaceGameDev568** [satisfactorymodding/SatisfactoryModManager#198]
**SMM Version:** `3.0.0-beta.3.1`

**OS:** `Windows 11`

In the latest SMM beta, I can no longer see virtual network drives added from Linux Samba shares in the "Path" option of the "Manage Servers" dialog. I have an SF DS on my Linux server in my home directory, which is shared on the local network with Samba. I connected to this Samba share on my Windows computer and have it mounted as drive `U:\`, but in the new SMM beta version, I only see the local drives attached to my system.
![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/95051062/228f434c-73b8-4ee9-bd98-b9d86c185010)

It will fail even if I enter the path manually (`U:\SatisfactoryDedicatedServer`), which did work before.

**Comment by mircearoata** [comment]
I could not reproduce this issue. Is there any specific samba or network mount configuration that you are using?
![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/19414258/21f81ca3-e9da-48d9-a01a-0e65b70343e9)
![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/19414258/83e1f01b-5989-4df5-aa1d-2541137f7e70)

**Comment by SpaceGameDev568** [comment]
Ahh, I restarted my PC + Server and it shows up now. No idea why SMM failed to detect it the first time. `¯\_(ツ)_/¯`
