### ISSUE TITLE
SMM3: If SML zip gets corrupted, SMM errors out instead of redownloading it

### ISSUE THREAD

**Issue by Th3Fanbus** [satisfactorymodding/SatisfactoryModManager#199]
[SMMDebug-2024-05-02-13-33-21.zip](https://github.com/satisfactorymodding/SatisfactoryModManager/files/15189136/SMMDebug-2024-05-02-13-33-21.zip)

**Comment by budak7273** [comment]
https://discord.com/channels/555424930502541343/834348739539238922/1237856456514998322
