### ISSUE TITLE
Latest version will not run via Kubuntu 24.04

### ISSUE THREAD

**Issue by steve7233** [satisfactorymodding/SatisfactoryModManager#200]
I ran it in a console to find out what the error was. Here is the output:
/home/vince/Downloads/SatisfactoryModManager_linux_amd64: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

Looks like a GTK error.

**Comment by mircearoata** [comment]
It looks like webkit2gtk-4.0 is no longer available on Ubuntu 24.04 and I'm assuming the latest Debian as well.

I've seen a couple of weeks ago that wails added support for linking against webkit2gtk-4.1, but the version has not yet been released. As far as I can tell, 4.1 is available in all supported versions of distros (so not including extended support), so updating SMM to it when it becomes available in wails should be fine.

I think a longer term solution would be providing an AppImage as well, and wails3 will have builtin support for that, but for now updating to 4.1 should be good for a few years.

**Comment by SparklesReal** [comment]
Just wanna say same problem if it matters

**Comment by SparklesReal** [comment]
sudo apt update
sudo apt install libwebkit2gtk-4.0-dev

Worked to start it but insta crash:
./SatisfactoryModManager_linux_amd64: symbol lookup error: ./SatisfactoryModManager_linux_amd64: undefined symbol: webkit_javascript_result_get_js_value

**Comment by mircearoata** [comment]
The wails version supporting webkit2gtk-4.1 released a few weeks ago, and I have also set up the appimage build script based on wails3's, so the next release is going to use this.

Unfortunately, I don't know when that release will be just yet, because I was planning to get a few more things in, but they are taking more time than expected. In the meantime, though, you can download the `build-linux` artifact from the latest actions run, which is built using webkit2gtk-4.1

**Comment by SparklesReal** [comment]
> The wails version supporting webkit2gtk-4.1 released a few weeks ago, and I have also set up the appimage build script based on wails3's, so the next release is going to use this.
> 
> Unfortunately, I don't know when that release will be just yet, because I was planning to get a few more things in, but they are taking more time than expected. In the meantime, though, you can download the `build-linux` artifact from the latest actions run, which is built using webkit2gtk-4.1

That worked, thanks!

**Comment by SoulInfernoDE** [comment]
_______________
_**Also linking against v4.1 seems to work for me:**_

![grafik](https://github.com/user-attachments/assets/2b282037-93c7-4d18-a717-f4b16a373d74)
**`sudo ln -s /lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so.0.13.6 /lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37`**



![grafik](https://github.com/user-attachments/assets/57d49706-ba8f-4c6d-a31b-bfc03d39961a)
**`sudo ln -s /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.1.so.0.5.6 /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18`**

________________


![grafik](https://github.com/user-attachments/assets/107130aa-fa4b-4cb8-9003-4b4159ded7b3)



![grafik](https://github.com/user-attachments/assets/e2bc8569-b52f-454d-8958-83cbf1cb514c)

![grafik](https://github.com/user-attachments/assets/f770646b-41a6-4f62-aa5b-3ddfc58ea2ef)

**Comment by TheFuze** [comment]
I'm on Nobara and also cannot run OOTB. an AppImage would be fantastic.

**Comment by aravol** [comment]
> _**Also linking against v4.1 seems to work for me:**_

This worked for me as well, however I also needed to link libsoup-2.4

```
sudo ln -s /lib/x86_64-linux-gnu/libsoup-3.0.so /lib/x86_64-linux-gnu/libsoup-2.4.so.1
```

Trying to install libsoup 2.4 did _not_ work, as it crashed after seeing both runtimes

**Comment by SoulInfernoDE** [comment]
Confirmed  -fixed it for me with version Satisfactory 1.0 and ModMan 3.0, too. 👍

**Comment by mircearoata** [comment]
v3.0.2 now correctly links against 4.1, and an AppImage is also available

**Comment by SoulInfernoDE** [comment]
Thanks for the fast fixes @mircearoata 

👍
