### ISSUE TITLE
programm start

### ISSUE THREAD

**Issue by Markus90MG** [satisfactorymodding/SatisfactoryModManager#202]
[SatisfactoryModManager.log](https://github.com/satisfactorymodding/SatisfactoryModManager/files/15494819/SatisfactoryModManager.log)

**Comment by mircearoata** [comment]
Hi! Can you please describe the issue you're running into?

**Comment by Markus90MG** [comment]
I start the exe but nothing happens, it says so in the task manager but nothing happens with SatisfactoryModManager v3.0.0-beta.4

**Comment by Markus90MG** [comment]
{"time":"2024-05-30T12:52:36.7696043+02:00","level":"ERROR","msg":"failed to add file to cache","file":"InventorySpace2_2.0.4_Windows.zip","err":"failed to read cache file: failed to read zip: zip: not a valid zip file"}
{"time":"2024-05-30T12:52:37.4093325+02:00","level":"ERROR","msg":"failed to add file to cache","file":"x3_signs_2.0.14_Windows.zip","err":"failed to read cache file: failed to read zip: zip: not a valid zip file"}
{"time":"2024-05-30T12:52:37.4400188+02:00","level":"INFO","msg":"connecting to sftp"}

**Comment by mircearoata** [comment]
Those messages are not something that would stop SMM from loading, just mentioning corrupt cached mods that will be redownloaded the next time they are needed.

Does SMM show up in the taskbar? Does it disappear from task manager after a while or do you have to kill it? If you uninstall it and install the previous beta version, does that load?

Can you edit `%appdata%\SatisfactoryModManager\settings.json` and change `updateCheckMode` from `launch` to `ask` and see if that allows SMM to load?

**Comment by mircearoata** [comment]
Which of the suggestions fixed the issue?
