### ISSUE TITLE
After compiling happend nothing

### ISSUE THREAD

**Issue by Sasisda228** [satisfactorymodding/SatisfactoryModManager#205]
" wails dev" and server starting but app not running
" wails build" and app just not opening( fast close)
![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/43885390/2df65896-37d2-4146-98b5-9b548eab9195)

ps. 
![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/43885390/c0020430-d76a-479d-8b18-97f50de40b49)
size make doubts

**Comment by mircearoata** [comment]
What Windows version are you running? What is the WebView2 runtime version that you have installed? (check in Settings->Apps->"Microsoft Edge WebView2 Runtime") Something is failing when creating the WebView2 environment for some reason.

The size is just as expected ~17MB, so the app compiles fine, but the WebView2 runtime is failing to load, so the window can't be displayed.

**Comment by Sasisda228** [comment]
> What Windows version are you running? What is the WebView2 runtime version that you have installed? (check in Settings->Apps->"Microsoft Edge WebView2 Runtime") Something is failing when creating the WebView2 environment for some reason.
> 
> The size is just as expected ~17MB, so the app compiles fine, but the WebView2 runtime is failing to load, so the window can't be displayed.

![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/43885390/0c65088f-4876-4beb-8aec-b5671419c3ed)

thank for reply

**Comment by mircearoata** [comment]
I think that should be new enough (as far as I can tell it needs to be at least 94.x), but I do have 125.x installed. Try updating it by downloading the installer from https://developer.microsoft.com/en-us/microsoft-edge/webview2, either the evergreen bootstrapper, or, if that says it's already installed, the fixed version download on the right.

**Comment by budak7273** [comment]
Feel free to reopen if you're still encountering issues
