### ISSUE TITLE
On linux v3.0.0-beta.4 is just a white screen

### ISSUE THREAD

**Issue by marvin1099** [satisfactorymodding/SatisfactoryModManager#206]
On Linux the v3.0.0-beta.4 is just a white screen, 
I temporary downgraded to v3.0.0-beta.3.2, 
that works fine but v3.0.0-beta.4 seems broken for linux.

**Comment by mircearoata** [comment]
What distro and which version of it are you using? Can you run SMM from the terminal and upload the output of that? Also upload `~/.cache/SatisfactoryModManager/logs/SatisfactoryModManager.log` in case the contents of that aren't already logged to the terminal

**Comment by SoulInfernoDE** [comment]
Does work fine for me on linux, so knowing which linux you are using maybe helps to find the trouble:

![grafik](https://github.com/user-attachments/assets/d2427fae-1e52-4829-b07d-be2499d7afc3)

**Comment by steve7233** [comment]
I have the same problem in my system Kubuntu 24.04. It could be a Ubuntu problem.

**Comment by DarcSceptor** [comment]
I have the latest Linux Mint installed. I got the install downloaded but there is no application associated with amd64!!!
What file type is this? How do I install it on Linux Mint (new user)

**Comment by mircearoata** [comment]
Unlike windows, linux doesn't have the `.exe` extension to determine whether a file is executable or not. Any file can be executed, as long as it has the executable flag set on the file. Because the file is downloaded raw from the internet, it doesn't have that flag set, so you have to set it either by running `chmod +x <the file>`, or setting the flag in the file properties in your file explorer, usually is a checkbox or dropdown

**Comment by SoulInfernoDE** [comment]
Updated Linux Mint to latest release wilma v22 and had the same problem, fixed it by linking libwebkit2gtk v4.0 --> v4.1 like described here: 

https://github.com/satisfactorymodding/SatisfactoryModManager/issues/200#issuecomment-2257122187

**Comment by marvin1099** [comment]
that log file just containes:
{"time":"2024-08-07T21:12:03.011438542+02:00","level":"INFO","msg":"using local disk","path":"/home/marvin/.steam/steam/steamapps/common/Satisfactory"}

the commandline output is:
2024/08/07 21:10:00 INFO starting Satisfactory Mod Manager version=3.0.0-beta.4 commit=bffc4ee84e055b67252c1cd104c89bed3bf697b1 date=2024-05-29T18:23:35Z
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
Failed to create GBM buffer of size 2054x1050: Invalid argument
2024-08-07T21:10:01+02:00 INF disk/main.go:58 using local disk path=/home/marvin/.steam/steam/steamapps/common/Satisfactory
2024-08-07T21:11:49+02:00 INF SatisfactoryModManager/main.go:239 exiting Satisfactory Mod Manager

the window is just a white screen still here a screenshot:
![Screenshot_20240807_211033](https://github.com/user-attachments/assets/4d69388c-42fb-419f-a6d5-89160e523824)

**Comment by marvin1099** [comment]
Also im on arch so I tried:
> cd /usr/lib
> sudo ln -s libwebkit2gtk-4.1.so.0.13.6 libwebkit2gtk-4.0.so.37
ln: failed to create symbolic link 'libwebkit2gtk-4.0.so.37': File exists
> sudo ln -s libjavascriptcoregtk-4.1.so.0.5.6 libjavascriptcoregtk-4.0.so.18
ln: failed to create symbolic link 'libjavascriptcoregtk-4.0.so.18': File exists

So i not shure what else to do.
btw I have webkit2gtk-4.0 and have webkit2gtk-4.1.

**Comment by SoulInfernoDE** [comment]
Do you have a symbolic link from folder /usr/lib to /lib on arch, too?

Just a guess

**Comment by marvin1099** [comment]
> Do you have a symbolic link from folder /usr/lib to /lib on arch, too?
> 
> Just a guess

jep, I have that, is that an issue?

**Comment by SoulInfernoDE** [comment]
No i think that is needed.

Is it possible to uninstall libwebkit 4.0 without damaging arch system and then linking 4.1 to 4.0 ?
If yes maybe worth a try.

**Comment by marvin1099** [comment]
so basically i should try to delete the conflicting symlink files.
shure i try it.

**Comment by SoulInfernoDE** [comment]
I found this which reads like its kind of same behavior in another app:

https://github.com/tauri-apps/tauri/issues/8254#issuecomment-2040961729

and another one here:

https://github.com/tauri-apps/tauri/issues/9304#issuecomment-2028409103

But to try one of these i think a simple export before you start the modman is a good test if that would help like:

`export WEBKIT_DISABLE_DMABUF_RENDERER=1`
and
`export WEBKIT_DISABLE_COMPOSITING_MODE=1`

this two commands are only active as long as the terminal has not been closed in most cases.

So in my setup i use kernel 6.10.2 and ubuntu 24.04 with webkit 4.1 linked to 4.0 and a amd cpu and gpu with kind of latest mesa drivers which seems to work for me.

Would be interesting to know if any of the suggestions/ideas did got you running. :-)

**Comment by marvin1099** [comment]
that works yes can that be fixed in the app though,
im not shure if this will breack something.
om maby the files can be provided?

**Comment by marvin1099** [comment]
> I found this which reads like its kind of same behavior in another app:
> 
> [tauri-apps/tauri#8254 (comment)](https://github.com/tauri-apps/tauri/issues/8254#issuecomment-2040961729)
> 
> and another one here:
> 
> [tauri-apps/tauri#9304 (comment)](https://github.com/tauri-apps/tauri/issues/9304#issuecomment-2028409103)
> 
> But to try one of these i think a simple export before you start the modman is a good test if that would help like:
> 
> `export WEBKIT_DISABLE_DMABUF_RENDERER=1` and `export WEBKIT_DISABLE_COMPOSITING_MODE=1`
> 
> this two commands are only active as long as the terminal has not been closed in most cases.
> 
> So in my setup i use kernel 6.10.2 and ubuntu 24.04 with webkit 4.1 linked to 4.0 and a amd cpu and gpu with kind of latest mesa drivers which seems to work for me.
> 
> Would be interesting to know if any of the suggestions/ideas did got you running. :-)

nice this works,
thanks.

**Comment by marvin1099** [comment]
Actually my problem if fixed, but i think i sould work for other users by default right?
Therefore only the issue is fixed not the problem.
Well the question is it this a problem that is going to be solved or should this be closed once more?

**Comment by mircearoata** [comment]
Following the linked Tauri issues, and also some Wails and Lutris issues of this, it's an issue with recent versions of webkit2 and nvidia's proprietary drivers.

But it looks like wails already has a workaround for this, disabling hardware acceleration by default (https://github.com/wailsapp/wails/pull/3027). However, that only happens if no linux configuration is provided, which was the case before beta.4, and so this was not an issue then. But since setting the app icon and name (https://github.com/satisfactorymodding/SatisfactoryModManager/commit/48b3058f5be3066a13d66f3515bad37ba51282e8), that is no longer the case, so the hardware acceleration defaults to always, in turn causing this.

On-demand hardware acceleration is also an option, but I think it's best to restore the setting to never, as it has been in previous betas.

I'll push this fix soon, and you can try it by downloading the `build-linux` artifact of the actions run (will edit with link when the artifact is available). These builds are of the upcoming beta.5, which uses webkit2gtk-4.1, and also includes an AppImage that uses the bundled webkit2 version used when building. That version should also be 4.1-2.44.x, as that is the latest available in Ubuntu 22.04 repositories, but it might be worth testing, just in case.

**Comment by marvin1099** [comment]
Jep that new build works, nice, i assume this will be included in the next prerelease or release, so i will close this for real now.

**Comment by tazz4843** [comment]
I can still reproduce this issue on a Framework 16 (Ryzen 7 7840HS + iGPU) running Fedora 40. Both the AppImage and the bare binary from the latest master `build-linux` artifact show the same blank white screen. Neither `WEBKIT_DISABLE_DMABUF_RENDERER=1` nor `WEBKIT_DISABLE_COMPOSITING_MODE=1` have any effect. I have the same log output as posted above as well, nothing of use in it.

Just to confirm the version i'm running is latest git master:
```
2024-08-18T17:34:21-07:00 INF SatisfactoryModManager/main.go:53 starting Satisfactory Mod Manager version=3.0.0-beta.4+4f473c0 commit=4f473c06062b7811498f755b0fa8097ad49e4494 date=2024-08-11T05:46:04Z type=standalone
```

**Comment by SoulInfernoDE** [comment]
If i guess right you are using amd cpu and gpu like me?

i am not familiar with fedora but i can try to help - which webkit version do you use on fedora ?

**Comment by tazz4843** [comment]
```
> sudo dnf info webkit2gtk4.0
Installed Packages
Name         : webkit2gtk4.0
Version      : 2.44.1
```

```
> glxinfo | grep -i OpenGL
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon 780M (radeonsi, gfx1103_r1, LLVM 18.1.6, DRM 3.57, 6.10.4-200.fc40.x86_64)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.1.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

No updates are available in any Fedora repos as of typing this.

**Comment by tazz4843** [comment]
Looks like 4.0 can be uninstalled in favour of 4.1 without issues, but results in no change. Recent system update updated mesa (to 24.1.6) with no change either, still blank white screen and nothing of use in logs.

I've never used the X session on this laptop as I've never had any reason to try it.

**Comment by SoulInfernoDE** [comment]
Interesting, so you are on Wayland I guess?
I am using xorg which is working fine for me. As I understood correct Wayland is still under heavy development. Is it possible to use a Xorg Session (without heavy system modifications) to test if xorg works with your setup?

So from what I read the trouble belongs to how the graphics driver and libwebkitgtk tries to spawn a window.   I guess this may differ a bit from X and Wayland.

**Comment by SoulInfernoDE** [comment]
@tazz4843 hmh can you try using another signal handler by starting the Appimage like this:

`
WEBKIT_DISABLE_DMABUF_RENDERER=1 WEBKIT_DISABLE_COMPOSITING_MODE=1 JSC_SIGNAL_FOR_GC=40 ./SatisfactoryModManager_linux_amd64
`
