### ISSUE TITLE
"mod broken" tooltip origin too far left

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/SatisfactoryModManager#233]
![Image](https://github.com/user-attachments/assets/7e160332-fa58-4454-92ad-07d89210722b)

**Comment by KiwiHour** [comment]
Can't seem to reproduce this. What's your monitors resolution?

**Comment by mircearoata** [comment]
This has been fixed in v3.0.0. The tooltips were getting their position relative to the window rather than the hovered element, which was necessary for tooltips inside dropdowns, but broke for some reason for some other elements, like the compatibility info
