### ISSUE TITLE
[UX] Double-clicking the application title does not maximize/restore the window

### ISSUE THREAD

**Issue by mouse0270** [satisfactorymodding/SatisfactoryModManager#250]
When a user double-clicks the title bar of the application window, the expected behavior is that the window should either maximize (if it's not already maximized) or restore to its original size (if it's already maximized). However, this default behavior does not occur.

**Steps to Reproduce:**
1. Open the application.
2. Attempt to double-click the title bar.
3. Observe that the window does not maximize/restore as expected.

**Comment by mircearoata** [comment]
Fixed in v3.0.2
