### ISSUE TITLE
SMM freezes after updating mods

### ISSUE THREAD

**Issue by Crasben** [satisfactorymodding/SatisfactoryModManager#255]
The mod manager freezes after i update mods, i can still interact with the left menu (it opens the submenu) but it doesn't show that i clicked things until i restart the manager, same with mods, i can click on uninstall mod or enable/disable mod but it doesn't recognize it until i restart the manager. I have tried reinstalling the manager and I still have the same problem. I think this started with 3.0.1 and still happens in 3.0.2 [SatisfactoryModManager.log](https://github.com/user-attachments/files/17464186/SatisfactoryModManager.log)

**Comment by gOOvER** [comment]
i cant confirm this. work fine for me

**Comment by Crasben** [comment]
Here's a video i just made with SMM freezing [Video](https://youtu.be/k6FG96msg6U)
