### ISSUE TITLE
How to install SMM on a dedicated drive/folder ?

### ISSUE THREAD

**Issue by FrankBKK** [satisfactorymodding/SatisfactoryModManager#266]
Is there a way to install SMM on a specific drive/folder as on previous versions ? 

The latest 3.0.3 does not offer to select installation folder.

**Comment by mircearoata** [comment]
You can choose the install location, but you first have to uninstall any previous version of SMM (both v2 and v3), or else it is considered to be an update, so it uses the existing install location to perform the update

**Comment by FrankBKK** [comment]
Ah ok, that makes sense. 

Thanks for the clarification.
