### ISSUE TITLE
Mod-Manager does not start.

### ISSUE THREAD

**Issue by McBenjihood** [satisfactorymodding/SatisfactoryModManager#271]
Yeah, basically it just doesnt start. Doesnt matter if you double click, execute as admin or execute the file through cmd, it just doesnt start. Weirdly, it does start in a Windows 11 Virtual Machine. That is of no use to me tho, bc I dont wanna play insinde a VM. Can I provide something like a log or smth similar to be of more help? 

Video of me failing to open the file:
https://github.com/user-attachments/assets/a2bfd800-009f-42e3-a753-3cce60f8c25f

**Comment by mircearoata** [comment]
Solved on discord, the issue was a broken webview2 install after using windows debloating software. A clean reinstall of webview2 fixed it
