### ISSUE TITLE
Game Launch progress display

### ISSUE THREAD

**Issue by Gaalidas** [satisfactorymodding/SatisfactoryModManager#30]
I have this issue where, upon trying to launch the game, it will just sit there for a long time with no apparent activity.  I gather it's likely making changes to the environment to allow the game to load the modded data but, when you have a lot of mods installed, this seems to take a really long time.  Either a progress bar or perhaps an output display somewhere (even a status bar at the bottom of the application) to show that it hasn't failed would be really great.

**Comment by mircearoata** [comment]
SMLauncher isn't doing anything at that time, it just calls Epic to launch the game, so it can't get any output from it. If you have many mods SML will take some time to start, and you can enable the console in SML.cfg to see when the game starts (the console is opened as soon as the game starts, and you can see SML's progress there)
