### ISSUE TITLE
SML expects game version 119805

### ISSUE THREAD

**Issue by sn0w-Dogg0** [satisfactorymodding/SatisfactoryModManager#34]
Can't install mods because SML says it requires a newer game version than is actually available on stable release

![image](https://user-images.githubusercontent.com/31472989/80134051-73105a80-859e-11ea-8273-e9bc8048ed32.png)

it also fails on install of SatisfactoryModLoader 2.1.0 with the same message

**Comment by garywilson4** [comment]
getting same

**Comment by mircearoata** [comment]
See issue #31
