### ISSUE TITLE
Profile management: rename, import/export

### ISSUE THREAD

**Issue by mkaito** [satisfactorymodding/SatisfactoryModManager#42]
For those of us trying to play modded multiplayer, a silly and unnecessarily dangerous lifestyle, it would be very useful to have the ability to rename mod profiles, as well as import and export, mostly for easy sharing with other people in a multiplayer session.

**Comment by mircearoata** [comment]
Import/export have been added in v2.0.0, and renaming can be done as creating a new profile with copy current checked
