### ISSUE TITLE
Steam version support ETA?

### ISSUE THREAD

**Issue by LemonzDEV** [satisfactorymodding/SatisfactoryModManager#43]
Satisfactory has been released today (08/06/2020) on Steam...
Any eta to bring this fantastic project to be compatible with Steam version?

**Comment by SirChopwood** [comment]
Should be within the next few days. I recommend joining the discord to be up to date on this stuff over using Github issues.
https://discord.gg/b7Pbwp

**Comment by TalkierDisc05** [comment]
I want to know the same thing too

**Comment by dracosensei** [comment]
Please bring steam support ASAP! or atleast a walkthrough how to manually install mods for the steam version.

Thanks!!!

**Comment by SirChopwood** [comment]
Again... join the discord... steam version for launcher is in developement but manual install instructions are on there and have been since day 1.

**Comment by MihaNick94** [comment]
Can someone give a link to manually install mods without using a launcher? I just don’t know where to look.

**Comment by sehraf** [comment]
> Should be within the next few days. I recommend joining the discord to be up to date on this stuff over using Github issues.
> https://discord.gg/b7Pbwp

Link is invalid.

**Comment by theotherp** [comment]
Try https://discord.com/invite/TShj39G

**Comment by mircearoata** [comment]
In about a minute
