### ISSUE TITLE
ModLauncher not  looking for alternative Satisfactory install path

### ISSUE THREAD

**Issue by Tokelu** [satisfactorymodding/SatisfactoryModManager#44]
For some reason, i cannot use the modlauncher. meaning it starts up, but i cannot seen any existing mods (well, there are none yet) and i cannot install any mods.

If i read the debug message correctly it seems like its looking for a Satisfactory install on a specific path ? I have my games installed on another HD and i get this message: "No Satisfactory installs found"
as well as some errors i can't decipher see screenshot. 

![error-snip](https://user-images.githubusercontent.com/22745957/84565087-09732800-ad67-11ea-8950-de33685c015e.PNG)

**Comment by mircearoata** [comment]
It's not looking at a specific path. It gets the installs from Epic (and soon Steam too). Where did you get the game from?

**Comment by Foxxtail1** [comment]
Any way we could just manually set the path to the game instead?

**Comment by mircearoata** [comment]
Did you buy the game on Epic, Steam, or pirate?

**Comment by Foxxtail1** [comment]
On Steam, I've seen that it isn't supported yet, but the ability to manually select the game path would go a long way.

**Comment by mircearoata** [comment]
You can join the modding discord and type `>steam` to get instructions for installing mods on Steam.

You can't manually set the game path, because it's more than just install path that SMLauncher needs, mainly the version, but also EXP/EA, which can only be found in the Epic/Steam install data, which is not in the game install unfortunately

**Comment by Tokelu** [comment]
> It's not looking at a specific path. It gets the installs from Epic (and soon Steam too). Where did you get the game from?

Its a Steam bought game
