### ISSUE TITLE
SML dosen't detect Satisfactory installed from Epic Games Launcher.

### ISSUE THREAD

**Issue by FuchsPlayZ** [satisfactorymodding/SatisfactoryModManager#45]
So I bought Satisfactory a week ago and wanted to play with mods, but after installing and Launching the SML it didn't appear for some reason. I tried reinstalling the game, but that didn't work either.

**Comment by DizzyDJW** [comment]
It loads up with "Error: No Installs Found"
Satisfactory was on Epic Games Store LONG before Steam, how is this even able to happen?

Is it because the game is on my secondary drive?

I am not gonna repurchase the game through Steam just to play with mods.

**Comment by mircearoata** [comment]
Is this still an issue? If so, upload the debug info
