### ISSUE TITLE
Linux/Proton Support

### ISSUE THREAD

**Issue by folknor** [satisfactorymodding/SatisfactoryModManager#47]
Hi,

I was hoping I could request support for Linux? It seems that getting SMM working would be easy for someone who knows the environment (Vue/Electron, etc).

I had a go for a minute, and after changing package.json to
```
    "linux": {
      "icon": "build/icons/linux.png"
    },
```
then opening the `icon.icon` file in GIMP and saving the 512px layer as linux.png, the next thing I did was edit `node_modules/satisfactory-mod-manager-api/src/installFinder.ts` to add this

```ts
async function getInstallsSteamLinux(): Promise<InstallFindResult> {
  const steamPath = "/home/folk/.steam/steam";
  const steamAppsPath = path.join(steamPath, 'steamapps');
  const libraryfoldersManifest = vdf.parse(fs.readFileSync(path.join(steamAppsPath, 'libraryfolders.vdf'), 'utf8')) as SteamLibraryFoldersManifest;
  const libraryfolders = Object.entries(libraryfoldersManifest.LibraryFolders).filter(([key]) => /^\d+$/.test(key)).map((entry) => entry[1]);
  const installs: Array<SatisfactoryInstall> = [];
  await libraryfolders.forEachAsync(async (libraryFolder) => {
    const sfManifestPath = path.join(libraryFolder, 'steamapps', 'appmanifest_526870.acf');
    if (fs.existsSync(sfManifestPath)) {
      const manifest = vdf.parse(fs.readFileSync(sfManifestPath, 'utf8')) as SteamManifest;
      const fullInstallPath = path.join(libraryFolder, 'steamapps', 'common', manifest.AppState.installdir);
      const gameVersion = await getGameVersionFromExe(path.join(fullInstallPath, 'FactoryGame', 'Binaries', 'Win64', 'FactoryGame-Win64-Shipping.exe'));
      installs.push(new SatisfactoryInstall(
        `${manifest.AppState.name} ${manifest.AppState.UserConfig.betakey?.toLowerCase() === 'experimental' ? 'Experimental' : 'Early Access'} (Steam)`,
        gameVersion,
        manifest.AppState.UserConfig.betakey || 'EA',
        fullInstallPath,
        'steam://rungameid/526870',
      ));
    }
  });
  return { installs, invalidInstalls: [] };
}

async function getInstallsLinux(): Promise<InstallFindResult> {
  const { installs: steamInstalls, invalidInstalls: invalidSteamInstalls } = await getInstallsSteamLinux();
  return { installs: steamInstalls, invalidInstalls: invalidSteamInstalls };
}

export async function getInstalls(): Promise<InstallFindResult> {
  // TODO: other OSes
  return getInstallsLinux();
}
```
(Obviously that code hardcodes my username, which is not good. Also, the best way to support Linux would be to allow the user to select the Steam install folder.)

And now `yarn dist` builds a runnable executable for Linux (AppImage and Snap file), so that's very nice :-)

But it still doesn't work, there's a few errors in the log when I start SMM:

```
┏ Electron -------------------

  (electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.
  
┗ ----------------------------

┏ Electron -------------------

  (node:45185) ExtensionLoadWarning: Warnings loading extension at /home/folk/.config/Electron/extensions/nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
  
┗ ----------------------------

┏ Electron -------------------

  Checking for update
  
┗ ----------------------------

┏ Electron -------------------

  Error: Error: ENOENT: no such file or directory, open '/home/folk/Programs/SatisfactoryModManager/dist/electron/dev-app-update.yml'
  
┗ ----------------------------

┏ Electron -------------------

  (node:45185) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/folk/Programs/SatisfactoryModManager/dist/electron/dev-app-update.yml'
  
┗ ----------------------------

┏ Electron -------------------

  (node:45185) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
  (node:45185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  
┗ ----------------------------

┏ Electron -------------------

  (node:45232) Electron: Loading non-context-aware native module in renderer: '/home/folk/Programs/SatisfactoryModManager/node_modules/satisfactory-mod-manager-api/build/Release/smlVersion.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
  (node:45232) Electron: Loading non-context-aware native module in renderer: '/home/folk/Programs/SatisfactoryModManager/node_modules/satisfactory-mod-manager-api/build/Release/bootstrapperVersion.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
  
┗ ----------------------------
```

Can you perhaps tell me how to proceed, or take a look yourself?

Or maybe someone else will handle it :-)

**Comment by mircearoata** [comment]
I looked a bit into it, but the main issue is that it cannot get the installed SML and bootstrapper version from the dll because that relies on windows API, which is not available without wine, so that's something I'll have to look into later

Btw, this is kinda the wrong repo, since finding installs is handled by [SMM API](https://github.com/mircearoata/SatisfactoryModManagerAPI)

**Comment by folknor** [comment]
I apologize for filing it in the wrong repo.

Wine is available in any case, because Satisfactory can't be run without Proton at the moment. The Proton executable location can be found if you know where Steam is installed (default /home/user/.steam, but like I said it should be selectable by the user in the best case scenario).

Each game uses the default Proton version unless explicitly configured by the user (which is very common), in which case it must be parsed from `.steam/steam/config/config.vdf`, where a typical entry under the `CompatToolMapping` entry looks like

```
                                        "526870"
                                        {
                                                "name"          "Proton-5.9-GE-2-MF"
                                                "config"                ""
                                                "Priority"              "250"
                                        }
```

This `name` then has to be found in the folder `.steam/steam/compatibilitytools.d/`, where each subfolder (whose name you should ignore) contains a file called `compatibilitytool.vdf`, which contains for example

```"compatibilitytools"
{
  "compat_tools"
  {
    "Proton-5.9-GE-2-MF" // Internal name of this tool
    {
      // Can register this tool with Steam in two ways:
      //
      // - The tool can be placed as a subdirectory in compatibilitytools.d, in which case this
      //   should be '.'
      //
      // - This manifest can be placed directly in compatibilitytools.d, in which case this should
      //   be the relative or absolute path to the tool's dist directory.
      "install_path" "."

      // For this template, we're going to substitute the display_name key in here, e.g.:
      "display_name" "Proton-5.9-GE-2-MF"

      "from_oslist"  "windows"
      "to_oslist"    "linux"
    }
  }
}
```

The "internal name" is most likely the one used in `config.vdf`. If the game does not appear in `config.vdf`, or if `"name"` is empty, that means it uses the default proton version, which can be found in `steamapps/common/Proton 5.0` (at the moment). I'm not sure how Steam decides what is the default Proton install, but we can probably find out easily :-)

**Comment by TimDiekmann** [comment]
Why do we need Proton in this case anyway? The dlls are installed to `steamapps/common/Satisfactory`, just like under Windows and Electron should just work with linux.

**Comment by rosshadden** [comment]
Thanks for opening this issue. I was trying to run the mod manager exe with proton and getting a "Windows 7 or above is required" error.

**Comment by sehraf** [comment]
For the sake of record: Modding Satisfactory under Linux (using Steam version) works fine. 
You just need to do stuff manually, for example, download the required files and tell wine to preload the xinput dll. That's all!

**Comment by folknor** [comment]
Yes, thank you sehraf, your comment reminded me - I want to explain here how to get mods loaded under Linux without the manager, just in case someone is wondering (which I think is likely):

1. Follow this guide https://docs.ficsit.app/satisfactory-modding/2.1.0/ManualInstallDirections.html (in that guide, "game root" means `/Steam/steamapps/common/Satisfactory`)
1. Right-click Satisfactory in Steam
1. Open `Properties`
1. Click the `Set launch options...` button
1. Enter `WINEDLLOVERRIDES="msdia140.dll,xinput1_3.dll=n,b" %command%`

And now mods should work fine. At least they do for me.

**Comment by jonchampagne** [comment]
For anyone stumbling upon this thread later, folknor's provided link is broken. The fixed correct link is https://docs.ficsit.app/satisfactory-modding/2.2.0/ManualInstallDirections.html

Alternatively, you can go to https://docs.ficsit.app and select Manual installation on the left.

**Comment by DBerke** [comment]
Can confirm that the process folknor outlined worked for me too (had to find the correct link on my own, so thanks jonchampagne for including it for future reference).

**Comment by x10an14** [comment]
I was unable to parse how to install mods from @folknor's description (step 1).

So I spent some time and made a PR explaining step 1 =)
https://github.com/satisfactorymodding/Documentation/pull/31

**Comment by mircearoata** [comment]
It's finally here!
