### ISSUE TITLE
SMM

### ISSUE THREAD

**Issue by Giehek** [satisfactorymodding/SatisfactoryModManager#48]
SMM is loading forever
![Adnotacja 2020-06-21 115315](https://user-images.githubusercontent.com/63113462/85221656-d1e32c00-b3b5-11ea-9e56-ebc9f28b5972.png)

**Comment by mircearoata** [comment]
Press ctrl+shift+i, then go to the console tab and send a screenshot of that

**Comment by Giehek** [comment]
![image](https://user-images.githubusercontent.com/63113462/85221753-d5c37e00-b3b6-11ea-91d8-d6830abdeb6f.png)

**Comment by mircearoata** [comment]
That's a warning, is there any error?

**Comment by Giehek** [comment]
![image](https://user-images.githubusercontent.com/63113462/85221805-2d61e980-b3b7-11ea-9db4-16f027a85683.png)

**Comment by mircearoata** [comment]
Looks like one of the mods downloaded is corrupted, and the error isn't handled. I'm looking into it. Try deleting `%localappdata%\SatisfactoryModManager\downloadCache`

**Comment by Giehek** [comment]
i must delete folder downloadCache or delete folders in downloadCache?

**Comment by Giehek** [comment]
i from Poland and my english is not god

**Comment by Giehek** [comment]
IT WORKS!
Thanks mircearoata

**Comment by mircearoata** [comment]
It doesn't matter, but deleting the downloadCache folder is quicker

**Comment by mircearoata** [comment]
Fixed in v2.1.0
