### ISSUE TITLE
Flying creates shudder movement for second player in multiplayer

### ISSUE THREAD

**Issue by duganm** [satisfactorymodding/SatisfactoryModManager#49]
Hello,

I'm joining a friend of mine's server where he is hosting, and I've applied the same mods that he has in place. The list of mods are: MoarFactory, MoarAssets, MoarDevice. When I activate the fly mode while holding the tablet, I experience "shudder" movement and cannot fly at all but he's still able to fly around in the server.

**Comment by mircearoata** [comment]
This is not the place to report it. Report the bug to the author of the mod
