### ISSUE TITLE
 SatisfactoryModManager wont update

### ISSUE THREAD

**Issue by MaxGojko** [satisfactorymodding/SatisfactoryModManager#52]
The SatisfactoryModManager starts updating(i can see this in the task manager: 10mbit/s usage) after that it has 2-4% CPU usage and doesn't do much(I waited 3 times more than 15min). I tried: restarting, starting the program as admin and reinstalling. 
Where can i find the logs?

**Comment by mircearoata** [comment]
The log file that contains auto-update logs is `%appdata%\satisfactory-mod-manager-gui\logs\main.log`

If you download the latest version from the releases page and install it to the same location as the current one is installed it will work, but please send the log, there have been a few reports of this issue

**Comment by MaxGojko** [comment]
![grafik](https://user-images.githubusercontent.com/46938385/86615669-10333a80-bfb5-11ea-905b-3fa599eaa938.png)
I can't find the folder

**Comment by mircearoata** [comment]
Oh... yeah... I added logging of the update in v2.1.0...
You can start the app from cmd and it will have the output there

**Comment by MaxGojko** [comment]
I already updated now, sry

**Comment by mircearoata** [comment]
It's ok, there might be someone who gets the issue again later
