### ISSUE TITLE
Crash on exit every time.

### ISSUE THREAD

**Issue by LordBSD** [satisfactorymodding/SatisfactoryModManager#56]
Hi and thanks for your hard work this is a great mod loader. The only thing is i dont know if i am doing anything wrong but both on the experimental branch and regular branch of satisfactory, when i exit my game with mod loader and just one mod loaded, (i tried two different ones as well.) the game crashes on exit. It wouldnt be so bad if it didnt still see it as running when i went to go play again. I cant seem to find anything in task manager and I have to reboot before I go for another session. Thanks for any help and let me know what you need and how i can get it for you.

**Comment by LordBSD** [comment]
Heres the log for you. 

`Version: 125236, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Unknown, IsUsingMods: Yes

Unhandled exception

FactoryGame_Win64_Shipping!TSet<TTuple<FString,FConfigFile>,TDefaultMapHashableKeyFuncs<FString,FConfigFile,0>,FDefaultSetAllocator>::FindId() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\containers\set.h:643]
FactoryGame_Win64_Shipping!FConfigCacheIni::Find() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\configcacheini.cpp:1658]
FactoryGame_Win64_Shipping!FConfigCacheIni::EmptySection() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\configcacheini.cpp:2092]
FactoryGame_Win64_Shipping!FWindowsApplication::ShutDownAfterError() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\applicationcore\private\windows\windowsapplication.cpp:236]
FactoryGame_Win64_Shipping!TBaseRawMethodDelegateInstance<1,SWaapiPicker,void __cdecl(void)>::ExecuteIfSafe() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:518]
FactoryGame_Win64_Shipping!TBaseMulticastDelegate<void>::Broadcast() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:977]
FactoryGame_Win64_Shipping!FWindowsErrorOutputDevice::HandleError() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:118]
FactoryGame_Win64_Shipping!FWindowsErrorOutputDevice::Serialize() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:83]
FactoryGame_Win64_Shipping!FOutputDevice::LogfImpl() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
FactoryGame_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:101]
FactoryGame_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:439]
FactoryGame_Win64_Shipping!FOutputDeviceRedirector::TearDown() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\private\misc\outputdeviceredirector.cpp:265]
FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:299]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll`

**Comment by mircearoata** [comment]
This is the wrong repo, this is the mod manager, not the mod loader. And it is a known issue, it is caused by the log file being open from a different thread
