### ISSUE TITLE
False positive "Game is running"

### ISSUE THREAD

**Issue by abesto** [satisfactorymodding/SatisfactoryModManager#63]
Satisfactory Mod Manager thinks that Satisfactory is running. It isn't, promise! Checked the task manager as well for any Satisfactory processes hiding, found none.
* Mod updates / installation fail saying the game is running
* There's a grey "Game is running" text at the bottom

Versions:
* SMM 2.1.2
* Satisfactory Steam Experimental CL125236 (as detected by SMM)
* SML 2.2.1

Attaching freshly generated debug log.
[SMMDebug_2020-7-26_17-4-28.zip](https://github.com/satisfactorymodding/SatisfactoryModManager/files/5131294/SMMDebug_2020-7-26_17-4-28.zip)

**Comment by mircearoata** [comment]
SMM runs `tasklist` or `wmic process` to find if there are any `FactoryGame-Win64-Shipping.exe` running. If Windows says there are, SMM will assume it is right. Next time it happens, send the output of `wmic process where name="FactoryGame-Win64-Shipping.exe"`, maybe the process is terminated but not responding or something

**Comment by abesto** [comment]
Good to know, thank you. That should also make it fairly easy to forcefully kill the offending process. Meanwhile I had to reboot, and SMM now (unsurprisingly) does *not* think that Satisfactory is running. Thank you for the response, I think we can consider this resolved for the moment.
