### ISSUE TITLE
Install in Steam Play

### ISSUE THREAD

**Issue by steve7233** [satisfactorymodding/SatisfactoryModManager#65]
I use Linux, not Windows. I run Steam for Linux and use Steam Play to play Satisfactory. How do I install the ModManager in this setup? My game is installed in /steam1/steamapps/common/Satisfactory/ steam1 is the label I used when I formated my SSD. It's probably called Z or some letter by the wine program that Steam Play uses. The Steam Play project is on GitHub if you need to ask them something.

**Comment by mircearoata** [comment]
Linux support in v2.2.0

**Comment by steve7233** [comment]
Thanks. I got it working now. Just letting you know in case it helps to know which distros and versions folks are running for future versions, I am running Kubuntu 20.04 that's Ubuntu but instead of Gnome, it uses Plasmoid and the KDE suite of software.
