### ISSUE TITLE
mods folder nuked on first launch

### ISSUE THREAD

**Issue by folknor** [satisfactorymodding/SatisfactoryModManager#66]
Hi, thanks so much for Linux support - and AppImage was the best choice you could've made. Excellent!

So, on first launch it seems SMM nuked my mods/ folder, is that correct? Or was it a Satisfactory patch that did it?

I have no problem with SMM doing this, but it would be great if you did some log output to stdout/err for each mod that is deleted.

I had no problem remembering the mods I had installed, fortunately. And also, it was present in the old `SatisfactoryModLoader.log`, like

```
[INFO] Post-initializing mod content packages...
[INFO] Post-initializing mod /Game/Letters/InitMod.InitMod_C
[INFO] Post-initializing mod /Game/AlreadyPaintedWalls/InitMod.InitMod_C
[INFO] Post-initializing mod /Game/ExoSuitMod/InitMod.InitMod_C
[INFO] Post-initializing mod /Game/FLAGSMod/InitMod.InitMod_C
[INFO] Post-initializing mod /Game/FLAGGONFICSIT/InitMod.InitMod_C
[INFO] Post-initializing mod /Game/HyperBoosters/InitMod.InitMod_C
[INFO] Post-initializing mod /Game/GrenadesMod/InitMod.InitMod_C
... etc
```

Here's all the log output I got from my first session of SMM;

```
./Satisfactory-Mod-Manager.AppImage
20:47:44.890 › Checking for update
20:47:45.741 › Update for version 2.2.0 is not available (latest version: 2.2.0, downgrade is disallowed).
20:47:47.625 › Checking for update
20:47:47.912 › Update for version 2.2.0 is not available (latest version: 2.2.0, downgrade is disallowed).
20:52:47.635 › Checking for update
20:52:48.383 › Update for version 2.2.0 is not available (latest version: 2.2.0, downgrade is disallowed).
20:57:47.713 › Checking for update
20:57:48.942 › Update for version 2.2.0 is not available (latest version: 2.2.0, downgrade is disallowed).

```

If I am correct and SMM nuked the folder, you might want to mention this in the release notes or readme, or perhaps add logging and release a small update for it?

Thanks again!

**Comment by folknor** [comment]
(It might be worth noting that I never manually checked for an update to SMM, it just did that 4 times in 10 minutes by itself.)

**Comment by mircearoata** [comment]
Yes, that is correct, because it validates the mod install to the manifest: nothing. It can't add the mods to the manifest because it can't tell that you never used SMM before on that install.

I will add to the release notes that you should write down the mods you had, or check the SML log for the list.

**Comment by folknor** [comment]
Alright, no worries. Thank you! If you want to add more log output, linux users always enjoy that :-)
