### ISSUE TITLE
POP OS , SMM wrong location

### ISSUE THREAD

**Issue by xenon205** [satisfactorymodding/SatisfactoryModManager#69]
"Error
1 Satisfactory install was found, but it points to a folder that doesn't exist.
"/home/name/Games/epic-games-store/drive_z/mnt/NVME700GB/Games/Epic Games/SatisfactoryEarlyAccess"
Seems wrong? Generate debug info and send it over on the modding discord in #help-using-mods"

Real location of this game is : /home/name/Games/epic-games-store/dosdevices/z:/mnt/NVME700GB/Games/Epic Games

I tried to generate debug file but it isn't saving anything. SMM version 2.2.1

Why not add manual option ?

**Comment by mircearoata** [comment]
Fixed in v2.3.0

And because it's not worth it when the fix is as easy as replacing `drive_X` with `dosdevices/X:`
