### ISSUE TITLE
infinite load

### ISSUE THREAD

**Issue by CoutoSH** [satisfactorymodding/SatisfactoryModManager#71]
the SMM get stunk in a infinite loading.... 

https://prnt.sc/vi4qwn

it's like this for like a hour or so

**Comment by mircearoata** [comment]
I am aware of this issue, but not sure why it only happens to some people. Will be fixed in the next version, or I can send a version which fixes it. I'll probably release the version this weekend, still have some things to fix

**Comment by senic35** [comment]
Same issue here with game on Epic Games.

**Comment by mircearoata** [comment]
Fixed in v2.3.0
