### ISSUE TITLE
Mod Manager doesn't launch

### ISSUE THREAD

**Issue by h3551** [satisfactorymodding/SatisfactoryModManager#73]
The SMM won't launch.

Triedd to fix the issue for about 4 hours with the MSSupport team today.

**Comment by mircearoata** [comment]
Can you explain what happens exactly? The installer doesn't launch? The app doesn't launch after installing? The game doesn't launch?

**Comment by RedstonedLife** [comment]
Apparently after installation and enabling the `Run SMM` when its done installing. runs it, but on the way it fucks with my pc. fucks in a way which
A. I can't open apps. not via Windows. not even from my task bar and Windows+R window
B. Windows just doesn't respond to clicks. except for when I bring up to menu.
That's about it.
I'll see what else I can do.

**Comment by mircearoata** [comment]
The app is just a basic electron app, much less complex than discord, or slack, or similar apps made with electron, and the installer is made with NSIS, which is one of the most used installer tools, so I don't know how I can help with your issue

**Comment by RICHARD712LEI** [comment]
al iniciar el satisfactory mod manager me sale esto:
 Error
No Satisfactory installs found.
Seems wrong? Generate debug info and send it over on the modding discord in #help-using-mods
me pueden dar una mano?

**Comment by h3551** [comment]
The current release of the SMM is launching fine.
