### ISSUE TITLE
Search Issues with Space

### ISSUE THREAD

**Issue by Stevoni** [satisfactorymodding/SatisfactoryModManager#74]
There seems to be an issue with searching for mods with spaces.

As I'm searching for "[Wall Pipe Supports](https://ficsit.app/mod/6yFR96phoYG8rP)", the search continues until I type the P after the space and the results go blank.

![image](https://user-images.githubusercontent.com/971593/100949472-f9dfcb00-34cf-11eb-8434-c139c2cf0daf.png)
![image](https://user-images.githubusercontent.com/971593/100949489-019f6f80-34d0-11eb-8c88-8a2923edaa9d.png)

**Comment by mircearoata** [comment]
Fixed in v2.4.0. I configured the fuse.js fuzzy search wrong
