### ISSUE TITLE
SMM stuck while installing 

### ISSUE THREAD

**Issue by itsdrwho99** [satisfactorymodding/SatisfactoryModManager#75]
its stuck on this 
any help ?
![s6gitx28a5361](https://user-images.githubusercontent.com/75478421/101153933-b69b6e80-362d-11eb-9b51-4fc6f93ba97e.png)

**Comment by Obliviant** [comment]
same here.. in the middle of installing it's just aborted.. also when using the installer as admin

**Comment by mircearoata** [comment]
Closing as this was a SMM2 issue, and SMM3 is now released
