### ISSUE TITLE
Can't start Satisfactory Modded

### ISSUE THREAD

**Issue by j54j6** [satisfactorymodding/SatisfactoryModManager#79]
I've looked a couple of Tutorials now and tons of issue requests on reddit and etc. but nothing helps me...

I've installed Satisfactory and ModManager new - in vanilla mode it worked without problems but if run the default "modded" profile the game can't start anymore (with 0 mods installed and with mods too...)
One thing I've seen is that a big part of the tutorials use the early access version of the game but unfortunately i can't install this version I only have the version SatisFactory Experimental (Epic Games) - CL141270 - SML v2.2.1 (I've changed SML down to v2.2.0 stepwise but nothing worked...

I've collected some logs but i can't find an error that depends on uninstalled software...

Logs:
Metadata.json: https://pastebin.com/2rwL199x (extracted by generate debug info)
SatisfactoryModManager.log: https://pastebin.com/yUBhVcZ7
Satsfactory itself doesn't log anything...

Hope anyone can help me ^^

**Comment by mircearoata** [comment]
Mods don't work with the new engine which is on Experimental yet. Use Early Access instead.

https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/70
