### ISSUE TITLE
Fix Update 4 Compatibility

### ISSUE THREAD

**Issue by RogWilco** [satisfactorymodding/SatisfactoryModManager#83]
I'm sure this is known, but didn't see an issue created for it yet. The current SMM release doesn't seem to work with the game after update 4 (confirmed on 0.4.3 build 147217). Most likely related to the Unreal engine upgrade.

Launching SMM results in an un-dismissable modal complaining that the satisfactory install directory doesn't exist, which of course it does (permissions issue?). Looks like this (can't interact with the UI at all):

![capture](https://user-images.githubusercontent.com/325622/111885914-cbef9b00-8987-11eb-829f-92f6f7e2bf7d.png)

Debug Info: [SMMDebug_2021-3-20_21-16-49.zip](https://github.com/satisfactorymodding/SatisfactoryModManager/files/6176442/SMMDebug_2021-3-20_21-16-49.zip)

**Comment by RogWilco** [comment]
Pretty sure the errors in the log are unrelated (looks like an API issue with ficsit.app):

```
2021-03-20 14:04:32:279	[ERROR]	Error getting data from ficsit.app: Network error: Unexpected token < in JSON at position 0. Trace:
Error: Network error: Unexpected token < in JSON at position 0
    at new ApolloError (C:\Program Files\Satisfactory Mod Manager\resources\app.asar\node_modules\apollo-client\bundle.umd.js:92:26)
    at C:\Program Files\Satisfactory Mod Manager\resources\app.asar\node_modules\apollo-client\bundle.umd.js:1588:34
    at C:\Program Files\Satisfactory Mod Manager\resources\app.asar\node_modules\apollo-client\bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at C:\Program Files\Satisfactory Mod Manager\resources\app.asar\node_modules\apollo-client\bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (C:\Program Files\Satisfactory Mod Manager\resources\app.asar\node_modules\apollo-client\bundle.umd.js:2004:20)
    at C:\Program Files\Satisfactory Mod Manager\resources\app.asar\node_modules\apollo-client\bundle.umd.js:1483:29
```

**Comment by lilbigmouth** [comment]
Workaround to close this for the time being on Windows:

Right click the application in the taskbar and select close window.

**Comment by Gimcrack** [comment]
Not sure if it helps, but this is the contents of the `SatisfactoryModManager.log` file if I click *Generate Debug Info*

```
2021-03-25 16:48:14:572	[INFO]	Set debug mode to false
2021-03-25 16:48:17:255	[DEBUG]	Epic Games Launcher is not installed
2021-03-25 16:49:40:876	[INFO]	Set debug mode to false
2021-03-25 16:49:43:460	[DEBUG]	Epic Games Launcher is not installed
```

**Comment by dFlynnSo** [comment]
> Not sure if it helps, but this is the contents of the `SatisfactoryModManager.log` file if I click _Generate Debug Info_
> 
> ```
> 2021-03-25 16:48:14:572	[INFO]	Set debug mode to false
> 2021-03-25 16:48:17:255	[DEBUG]	Epic Games Launcher is not installed
> 2021-03-25 16:49:40:876	[INFO]	Set debug mode to false
> 2021-03-25 16:49:43:460	[DEBUG]	Epic Games Launcher is not installed
> ```
> 
> edit: I forgot to mention I don't even use the Epic version. I'm on Steam.

Can confirm this for the Steam Version, same problem.

Works like a charm on Epic Version

**Comment by dFlynnSo** [comment]
> Not sure if it helps, but this is the contents of the `SatisfactoryModManager.log` file if I click _Generate Debug Info_
> 
> ```
> 2021-03-25 16:48:14:572	[INFO]	Set debug mode to false
> 2021-03-25 16:48:17:255	[DEBUG]	Epic Games Launcher is not installed
> 2021-03-25 16:49:40:876	[INFO]	Set debug mode to false
> 2021-03-25 16:49:43:460	[DEBUG]	Epic Games Launcher is not installed
> ```
> 
> edit: I forgot to mention I don't even use the Epic version. I'm on Steam.

Can confirm this for the Steam Version, same problem on my other Computer

**Comment by kreczko** [comment]
Also steam, but no errors in the log:

```
2021-04-01 20:54:06:817	[INFO]	Set debug mode to false
2021-04-01 20:54:09:197	[WARN]	UE manifest filtered all installs.
2021-04-01 20:55:51:844	[INFO]	Set debug mode to false
2021-04-01 20:55:53:794	[WARN]	UE manifest filtered all installs.
```

Error message comes from https://github.com/satisfactorymodding/SatisfactoryModManager/blob/6e93cee68074e51d715cc099b68150437ef6e62a/src/renderer/store.js#L319

which means that the install is not considered valid.

`getInstalls` from [mircearoata/SatisfactoryModManagerAPI](https://github.com/mircearoata/SatisfactoryModManagerAPI/blob/master/src/installfinders/windows/steam.ts#L77) considers an install valid if it can find
```javascript
const gameExe = path.join(fullInstallPath, 'FactoryGame', 'Binaries', 'Win64', 'FactoryGame-Win64-Shipping.exe');
```

However, in Update 4 this file does not exist:

```
FactoryGame
├── Binaries
│   └── Win64
│       ├── UE4-CoffeeCore-Win64-Shipping.dll
│       ├── UE4-CoffeeCore-Win64-Shipping.pdb
│       ├── UE4-FactoryGame-Win64-Shipping.dll
│       ├── UE4-FactoryGame-Win64-Shipping.pdb
│       ├── UE4-GameAnalyticsModule-Win64-Shipping.dll
│       ├── UE4-GameAnalyticsModule-Win64-Shipping.pdb
│       ├── UE4-Win64-Shipping.modules
│       └── dbgcore.dll
```

The only EXE files in the install are
```
Satisfactory$ find . -name "*.exe"
./Engine/Binaries/Win64/CrashReportClient.exe
./Engine/Binaries/Win64/UE4-Win64-Shipping.exe
./Engine/Binaries/Win64/UnrealCEFSubProcess.exe
./Engine/Extras/Redist/en-us/UE4PrereqSetup_x64.exe
./FactoryGame.exe
```
The closest match is `./Engine/Binaries/Win64/UE4-Win64-Shipping.exe`

So the question is: Is this going to stay like this for the experimental Update 4 or is it something that needs changing for the proper release in two weeks time?
Also, should this issue be opened in https://github.com/mircearoata/SatisfactoryModManagerAPI ?

**Comment by mircearoata** [comment]
SMM v2.4.0 now supports SML 3.0 and by extent Update 4
