### ISSUE TITLE
Hover animation

### ISSUE THREAD

**Issue by LNonymous** [satisfactorymodding/SatisfactoryModManager#88]
If you move your mouse very fast over the "Remove" and "Favourite" button in your mod the hover animation will stay unitl you hover over it again. 
![Satisfactory Modmanager](https://user-images.githubusercontent.com/52412886/114503821-2817a900-9c2e-11eb-906c-916af2601b06.png)

**Comment by mircearoata** [comment]
Might have been fixed in v2.4.1. Let me know if it still happens

**Comment by LNonymous** [comment]
yes with the new version it got fixed
