### ISSUE TITLE
Update to 2.4 doesn't work

### ISSUE THREAD

**Issue by deejaykris** [satisfactorymodding/SatisfactoryModManager#89]
Hello,
i wanted to start the SMM and an update apears. But the update doesn't work and i get an error while installing. 

![Installation_error](https://user-images.githubusercontent.com/72092768/114504423-24385680-9c2f-11eb-8d2e-78a6c8db021b.png)

It's in german, but maybe someone can help me. I also tried to download the latest version and uninstall the latest, but it still doesn't work.

best regards

**Comment by Urganot** [comment]
It looks like the manager is sill opened in the background. make sure its closed. also restarting your pc might help

**Comment by deejaykris** [comment]
Okay, i will try it today again. But i downladed the latest version and uninstall the old. But the problem was the same. Maybe i should take a look in the task manager.

**Comment by deejaykris** [comment]
SMM was completly removed. I installed theee 2.4.0 version. When I started SMM, I saw the new overlay. The program wanted to do an update again with the same error.
:(

**Comment by HelpIamHavingProblem** [comment]
Starte es als Administrator

**Comment by deejaykris** [comment]
Hatte ich gemacht, alles mögliche! Das einzige, was am Ende geholfen hat, war den SMM in einen neuen Ordner zu installieren. Da ging dann auch die 2.4.1. strange
