### ISSUE TITLE
Game is not launching

### ISSUE THREAD

**Issue by NeoVanAlemania** [satisfactorymodding/SatisfactoryModManager#90]
Hello,

big thanks for updating the mod launcher to game update 4!

Even for Early Acces and Experimental build the game is not going to launch.
Whenever I press the "Launch Satisfactory" button it happens nothing...

I have already tried to re-install via the automatic installer without any difference.

**Comment by acantril** [comment]
I also have the same thing

**Comment by mircearoata** [comment]
Fixed in v2.4.1
