### ISSUE TITLE
SMM no longer starting game after updating to 2.4.0

### ISSUE THREAD

**Issue by Spanky265** [satisfactorymodding/SatisfactoryModManager#92]
Steam downloaded an update to Satisfactory and SMM updated to 2.4.0.  Now the Launch Satisfactory button just flashes when clicked and nothing else happens.  Included is the SMM Debug report.

[SMMDebug_2021-4-13_18-13-46.zip](https://github.com/satisfactorymodding/SatisfactoryModManager/files/6305857/SMMDebug_2021-4-13_18-13-46.zip)

**Comment by acantril** [comment]
having the same issue

**Comment by mircearoata** [comment]
Fixed in v2.4.1
