### ISSUE TITLE
List view does not update state when filter is changed

### ISSUE THREAD

**Issue by ST-DDT** [satisfactorymodding/SatisfactoryModManager#93]
![grafik](https://user-images.githubusercontent.com/1579362/114601247-96dc1d00-9c95-11eb-988f-0f4d68cc1124.png)

SMM v2.4.0 (Windows)

The mod shows, that it can be downloaded and be added to the favorites, but as you can see in the filter it should already be installed.

**Comment by mircearoata** [comment]
Fixed in v2.4.1. The problem was that somehow the v-else-if was simply not updating the icon to display. I fixed it somehow, but it might come back in the future on other branches of that v-else-if
