### ISSUE TITLE
Mod errors not explained

### ISSUE THREAD

**Issue by ST-DDT** [satisfactorymodding/SatisfactoryModManager#94]
![grafik](https://user-images.githubusercontent.com/1579362/114601981-66e14980-9c96-11eb-8ff3-438ea7ae51e6.png)

SMM 2.4.0 (Windows)

The mod list shows a warning/error/something, but there is no explanation why.

Might be related to https://github.com/satisfactorymodding/SatisfactoryModManager/issues/93 (aka it is only shown as error, but the actual error might be for something else)

**Comment by mircearoata** [comment]
Fixed the compatibility check in v2.4.1. This could have also been the mod being updated as SMM was getting the list of mods, so it got an incomplete list of versions, but the proper last updated timestamp.
