### ISSUE TITLE
Add filter for "latest-sml" compatible mods

### ISSUE THREAD

**Issue by ST-DDT** [satisfactorymodding/SatisfactoryModManager#95]
Currently it is almost impossible to filter for mods that are compatible with SML v3.0.0

SMM v2.4.0 (Windows)

**Comment by mircearoata** [comment]
The compatibility check has been fixed in v2.4.1, so you can now use the compatible filter. There are still some mods that specify the compatible SML versions incorrectly, which will show up as compatible.
