### ISSUE TITLE
Satisfactory Mod Manager starting Issue

### ISSUE THREAD

**Issue by Peckerhacker10203** [satisfactorymodding/SatisfactoryModManager#97]
Hi,
having a problem launching Satisfactory, details on the screenshot attached!

<img width="302" alt="Screenshot 2021-04-16 175828" src="https://user-images.githubusercontent.com/81530124/115051829-874f1500-9edd-11eb-903f-c424afb60705.png">

**Comment by Peckerhacker10203** [comment]
Reinstall

**Comment by zaratropia** [comment]
Looks like some mess up with shitty windows file permissions. Reinstall or "Run as Administrator".
