### ISSUE TITLE
Satisfactory Multiplayer issue

### ISSUE THREAD

**Issue by Peckerhacker10203** [satisfactorymodding/SatisfactoryModManager#98]
Hi,
I have a problem with joining a friends multiplayer session with mods. We installed both the same ones!

![20210416_201409](https://user-images.githubusercontent.com/81530124/115066812-59270080-9ef0-11eb-9c8f-4524e9bbf12b.jpg)

![20210416_201418](https://user-images.githubusercontent.com/81530124/115066840-60e6a500-9ef0-11eb-939d-f21174ffd3f5.jpg)

**Comment by dFlynnSo** [comment]
Same Error with only one Mod active

**Comment by mircearoata** [comment]
This is not a SMM issue, it is a SML issue, and we're already aware of it https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/81
