### ISSUE TITLE
Linux AppImage Connection Refused

### ISSUE THREAD

**Issue by MyrianneG** [satisfactorymodding/SatisfactoryModManager#99]
Using the new 3.0.0 AppImage on Linux with a fresh Satisfactory install and a fresh SMM download.

Application starts up fine but throws an error in the command line:
(satisfactory-mod-manager-gui:6193): IBUS-WARNING **: 18:02:04.468: Unable to connect to ibus: Could not connect: Connection refused
18:02:05.850 › Checking for update
18:02:05.978 › Update for version 2.4.1 is not available (latest version: 2.4.1, downgrade is disallowed).

If I try to download a mod, SMM gives me a popup window error that reads: Archive read error.

Not sure if it's useful to mention, but this was working fine just a few days ago when the "broken" version of the U4 SMM was released.  I also made sure all of the ports that SMM is trying to access are open on my firewall (though that shouldn't be a problem for outgoing connections anyway).

**Comment by mircearoata** [comment]
I'm not sure if the ibus warning affects anything, but the archive read error means a corrupted cached mod/SML. Clear the cache from the settings->Debug menu, and try to install the mod again

**Comment by MyrianneG** [comment]
That worked.  I'm kind of confused though, since I deleted two different directories with cache info when I reinstalled.  I'm guessing there must be a third somewhere.

Anyway, thanks for the help.  Closing this out.
